package org.xbery.artbeams.search.repository.mapper

import com.fasterxml.jackson.databind.ObjectMapper
import org.jooq.RecordUnmapper
import org.springframework.stereotype.Component
import org.xbery.artbeams.search.domain.SearchIndexEntry
import org.xbery.artbeams.jooq.schema.tables.records.SearchIndexRecord
import org.xbery.artbeams.jooq.schema.tables.references.SEARCH_INDEX

/**
 * Maps SearchIndexEntry domain object to database record.
 * @author Radek Beran
 */
@Component
class SearchIndexUnmapper(
    private val objectMapper: ObjectMapper
) : RecordUnmapper<SearchIndexEntry, SearchIndexRecord> {

    override fun unmap(entry: SearchIndexEntry): SearchIndexRecord {
        val record = SEARCH_INDEX.newRecord()
        record.id = entry.id
        record.entityType = entry.entityType.name
        record.entityId = entry.entityId
        record.title = entry.title
        record.description = entry.description
        record.keywords = entry.keywords
        record.slug = entry.slug
        // Note: searchVector is generated by database trigger/function, not set here
        record.searchVector = entry.searchVector
        record.metadata = if (entry.metadata.isNotEmpty()) {
            try {
                objectMapper.writeValueAsString(entry.metadata)
            } catch (e: Exception) {
                null
            }
        } else {
            null
        }
        record.validFrom = entry.validFrom
        record.validTo = entry.validTo
        record.created = entry.created
        record.modified = entry.modified
        return record
    }
}
