/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables.references


import org.xbery.artbeams.jooq.schema.tables.AntispamQuiz
import org.xbery.artbeams.jooq.schema.tables.ArticleCategory
import org.xbery.artbeams.jooq.schema.tables.Articles
import org.xbery.artbeams.jooq.schema.tables.AuthCode
import org.xbery.artbeams.jooq.schema.tables.Categories
import org.xbery.artbeams.jooq.schema.tables.Comments
import org.xbery.artbeams.jooq.schema.tables.Config
import org.xbery.artbeams.jooq.schema.tables.Consents
import org.xbery.artbeams.jooq.schema.tables.EntityAccessCount
import org.xbery.artbeams.jooq.schema.tables.Localisation
import org.xbery.artbeams.jooq.schema.tables.Media
import org.xbery.artbeams.jooq.schema.tables.NewsSubscription
import org.xbery.artbeams.jooq.schema.tables.OrderItems
import org.xbery.artbeams.jooq.schema.tables.Orders
import org.xbery.artbeams.jooq.schema.tables.Products
import org.xbery.artbeams.jooq.schema.tables.Queue
import org.xbery.artbeams.jooq.schema.tables.Roles
import org.xbery.artbeams.jooq.schema.tables.Sequences
import org.xbery.artbeams.jooq.schema.tables.UserAccess
import org.xbery.artbeams.jooq.schema.tables.UserProduct
import org.xbery.artbeams.jooq.schema.tables.UserRole
import org.xbery.artbeams.jooq.schema.tables.Users



/**
 * The table <code>antispam_quiz</code>.
 */
val ANTISPAM_QUIZ: AntispamQuiz = AntispamQuiz.ANTISPAM_QUIZ

/**
 * The table <code>article_category</code>.
 */
val ARTICLE_CATEGORY: ArticleCategory = ArticleCategory.ARTICLE_CATEGORY

/**
 * The table <code>articles</code>.
 */
val ARTICLES: Articles = Articles.ARTICLES

/**
 * The table <code>auth_code</code>.
 */
val AUTH_CODE: AuthCode = AuthCode.AUTH_CODE

/**
 * The table <code>categories</code>.
 */
val CATEGORIES: Categories = Categories.CATEGORIES

/**
 * The table <code>comments</code>.
 */
val COMMENTS: Comments = Comments.COMMENTS

/**
 * The table <code>config</code>.
 */
val CONFIG: Config = Config.CONFIG

/**
 * The table <code>consents</code>.
 */
val CONSENTS: Consents = Consents.CONSENTS

/**
 * The table <code>entity_access_count</code>.
 */
val ENTITY_ACCESS_COUNT: EntityAccessCount = EntityAccessCount.ENTITY_ACCESS_COUNT

/**
 * The table <code>localisation</code>.
 */
val LOCALISATION: Localisation = Localisation.LOCALISATION

/**
 * The table <code>media</code>.
 */
val MEDIA: Media = Media.MEDIA

/**
 * The table <code>news_subscription</code>.
 */
val NEWS_SUBSCRIPTION: NewsSubscription = NewsSubscription.NEWS_SUBSCRIPTION

/**
 * The table <code>order_items</code>.
 */
val ORDER_ITEMS: OrderItems = OrderItems.ORDER_ITEMS

/**
 * The table <code>orders</code>.
 */
val ORDERS: Orders = Orders.ORDERS

/**
 * The table <code>products</code>.
 */
val PRODUCTS: Products = Products.PRODUCTS

/**
 * The table <code>queue</code>.
 */
val QUEUE: Queue = Queue.QUEUE

/**
 * The table <code>roles</code>.
 */
val ROLES: Roles = Roles.ROLES

/**
 * The table <code>sequences</code>.
 */
val SEQUENCES: Sequences = Sequences.SEQUENCES

/**
 * The table <code>user_access</code>.
 */
val USER_ACCESS: UserAccess = UserAccess.USER_ACCESS

/**
 * The table <code>user_product</code>.
 */
val USER_PRODUCT: UserProduct = UserProduct.USER_PRODUCT

/**
 * The table <code>user_role</code>.
 */
val USER_ROLE: UserRole = UserRole.USER_ROLE

/**
 * The table <code>users</code>.
 */
val USERS: Users = Users.USERS
