/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables.records


import org.jooq.impl.TableRecordImpl
import org.xbery.artbeams.jooq.schema.tables.ArticleCategory


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ArticleCategoryRecord() : TableRecordImpl<ArticleCategoryRecord>(ArticleCategory.ARTICLE_CATEGORY) {

    open var articleId: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var categoryId: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    /**
     * Create a detached, initialised ArticleCategoryRecord
     */
    constructor(articleId: String? = null, categoryId: String? = null): this() {
        this.articleId = articleId
        this.categoryId = categoryId
        resetChangedOnNotNull()
    }
}
