/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables.records


import kotlinx.datetime.Instant

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import org.xbery.artbeams.jooq.schema.tables.Articles


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ArticlesRecord() : UpdatableRecordImpl<ArticlesRecord>(Articles.ARTICLES) {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var externalId: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var validFrom: Instant?
        set(value): Unit = set(2, value)
        get(): Instant? = get(2) as Instant?

    open var validTo: Instant?
        set(value): Unit = set(3, value)
        get(): Instant? = get(3) as Instant?

    open var created: Instant?
        set(value): Unit = set(4, value)
        get(): Instant? = get(4) as Instant?

    open var createdBy: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var modified: Instant?
        set(value): Unit = set(6, value)
        get(): Instant? = get(6) as Instant?

    open var modifiedBy: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var slug: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    open var title: String?
        set(value): Unit = set(9, value)
        get(): String? = get(9) as String?

    open var image: String?
        set(value): Unit = set(10, value)
        get(): String? = get(10) as String?

    open var perex: String?
        set(value): Unit = set(11, value)
        get(): String? = get(11) as String?

    open var body: String?
        set(value): Unit = set(12, value)
        get(): String? = get(12) as String?

    open var bodyMarkdown: String?
        set(value): Unit = set(13, value)
        get(): String? = get(13) as String?

    open var keywords: String?
        set(value): Unit = set(14, value)
        get(): String? = get(14) as String?

    open var showOnBlog: Boolean?
        set(value): Unit = set(15, value)
        get(): Boolean? = get(15) as Boolean?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised ArticlesRecord
     */
    constructor(id: String? = null, externalId: String? = null, validFrom: Instant? = null, validTo: Instant? = null, created: Instant? = null, createdBy: String? = null, modified: Instant? = null, modifiedBy: String? = null, slug: String? = null, title: String? = null, image: String? = null, perex: String? = null, body: String? = null, bodyMarkdown: String? = null, keywords: String? = null, showOnBlog: Boolean? = null): this() {
        this.id = id
        this.externalId = externalId
        this.validFrom = validFrom
        this.validTo = validTo
        this.created = created
        this.createdBy = createdBy
        this.modified = modified
        this.modifiedBy = modifiedBy
        this.slug = slug
        this.title = title
        this.image = image
        this.perex = perex
        this.body = body
        this.bodyMarkdown = bodyMarkdown
        this.keywords = keywords
        this.showOnBlog = showOnBlog
        resetChangedOnNotNull()
    }
}
