/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables.records


import java.time.LocalDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import org.xbery.artbeams.jooq.schema.tables.Categories


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CategoriesRecord() : UpdatableRecordImpl<CategoriesRecord>(Categories.CATEGORIES) {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var validFrom: LocalDateTime?
        set(value): Unit = set(1, value)
        get(): LocalDateTime? = get(1) as LocalDateTime?

    open var validTo: LocalDateTime?
        set(value): Unit = set(2, value)
        get(): LocalDateTime? = get(2) as LocalDateTime?

    open var created: LocalDateTime?
        set(value): Unit = set(3, value)
        get(): LocalDateTime? = get(3) as LocalDateTime?

    open var createdBy: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var modified: LocalDateTime?
        set(value): Unit = set(5, value)
        get(): LocalDateTime? = get(5) as LocalDateTime?

    open var modifiedBy: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var slug: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var title: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    open var description: String?
        set(value): Unit = set(9, value)
        get(): String? = get(9) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised CategoriesRecord
     */
    constructor(id: String? = null, validFrom: LocalDateTime? = null, validTo: LocalDateTime? = null, created: LocalDateTime? = null, createdBy: String? = null, modified: LocalDateTime? = null, modifiedBy: String? = null, slug: String? = null, title: String? = null, description: String? = null): this() {
        this.id = id
        this.validFrom = validFrom
        this.validTo = validTo
        this.created = created
        this.createdBy = createdBy
        this.modified = modified
        this.modifiedBy = modifiedBy
        this.slug = slug
        this.title = title
        this.description = description
        resetChangedOnNotNull()
    }
}
