/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables.records


import java.time.Instant

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import org.xbery.artbeams.jooq.schema.tables.Consents


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ConsentsRecord() : UpdatableRecordImpl<ConsentsRecord>(Consents.CONSENTS) {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var validFrom: Instant?
        set(value): Unit = set(1, value)
        get(): Instant? = get(1) as Instant?

    open var validTo: Instant?
        set(value): Unit = set(2, value)
        get(): Instant? = get(2) as Instant?

    open var login: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var consentType: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var originProductId: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised ConsentsRecord
     */
    constructor(id: String? = null, validFrom: Instant? = null, validTo: Instant? = null, login: String? = null, consentType: String? = null, originProductId: String? = null): this() {
        this.id = id
        this.validFrom = validFrom
        this.validTo = validTo
        this.login = login
        this.consentType = consentType
        this.originProductId = originProductId
        resetChangedOnNotNull()
    }
}
