/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables.records


import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl
import org.xbery.artbeams.jooq.schema.tables.EntityAccessCount


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class EntityAccessCountRecord() : UpdatableRecordImpl<EntityAccessCountRecord>(EntityAccessCount.ENTITY_ACCESS_COUNT) {

    open var entityType: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var entityId: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var accessCount: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<String?, String?> = super.key() as Record2<String?, String?>

    /**
     * Create a detached, initialised EntityAccessCountRecord
     */
    constructor(entityType: String? = null, entityId: String? = null, accessCount: Int? = null): this() {
        this.entityType = entityType
        this.entityId = entityId
        this.accessCount = accessCount
        resetChangedOnNotNull()
    }
}
