/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import org.xbery.artbeams.jooq.schema.tables.Localisation


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class LocalisationRecord() : UpdatableRecordImpl<LocalisationRecord>(Localisation.LOCALISATION) {

    open var entryKey: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var entryValue: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised LocalisationRecord
     */
    constructor(entryKey: String? = null, entryValue: String? = null): this() {
        this.entryKey = entryKey
        this.entryValue = entryValue
        resetChangedOnNotNull()
    }
}
