/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables.records


import java.time.Instant

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import org.xbery.artbeams.jooq.schema.tables.NewsSubscription


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class NewsSubscriptionRecord() : UpdatableRecordImpl<NewsSubscriptionRecord>(NewsSubscription.NEWS_SUBSCRIPTION) {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var email: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var created: Instant?
        set(value): Unit = set(2, value)
        get(): Instant? = get(2) as Instant?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised NewsSubscriptionRecord
     */
    constructor(id: String? = null, email: String? = null, created: Instant? = null): this() {
        this.id = id
        this.email = email
        this.created = created
        resetChangedOnNotNull()
    }
}
