/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables.records


import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl
import org.xbery.artbeams.jooq.schema.tables.ProductCourse


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ProductCourseRecord() : UpdatableRecordImpl<ProductCourseRecord>(ProductCourse.PRODUCT_COURSE) {

    open var productId: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var courseId: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<String?, String?> = super.key() as Record2<String?, String?>

    /**
     * Create a detached, initialised ProductCourseRecord
     */
    constructor(productId: String? = null, courseId: String? = null): this() {
        this.productId = productId
        this.courseId = courseId
        resetChangedOnNotNull()
    }
}
