/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables.records


import java.math.BigDecimal
import java.time.Instant

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import org.xbery.artbeams.jooq.schema.tables.Products


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ProductsRecord() : UpdatableRecordImpl<ProductsRecord>(Products.PRODUCTS) {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var created: Instant?
        set(value): Unit = set(1, value)
        get(): Instant? = get(1) as Instant?

    open var createdBy: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var modified: Instant?
        set(value): Unit = set(3, value)
        get(): Instant? = get(3) as Instant?

    open var modifiedBy: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var slug: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var title: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var subtitle: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var filename: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    open var listingImage: String?
        set(value): Unit = set(9, value)
        get(): String? = get(9) as String?

    open var image: String?
        set(value): Unit = set(10, value)
        get(): String? = get(10) as String?

    open var confirmationMailingGroupId: String?
        set(value): Unit = set(11, value)
        get(): String? = get(11) as String?

    open var mailingGroupId: String?
        set(value): Unit = set(12, value)
        get(): String? = get(12) as String?

    open var priceRegular: BigDecimal?
        set(value): Unit = set(13, value)
        get(): BigDecimal? = get(13) as BigDecimal?

    open var priceDiscounted: BigDecimal?
        set(value): Unit = set(14, value)
        get(): BigDecimal? = get(14) as BigDecimal?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised ProductsRecord
     */
    constructor(id: String? = null, created: Instant? = null, createdBy: String? = null, modified: Instant? = null, modifiedBy: String? = null, slug: String? = null, title: String? = null, subtitle: String? = null, filename: String? = null, listingImage: String? = null, image: String? = null, confirmationMailingGroupId: String? = null, mailingGroupId: String? = null, priceRegular: BigDecimal? = null, priceDiscounted: BigDecimal? = null): this() {
        this.id = id
        this.created = created
        this.createdBy = createdBy
        this.modified = modified
        this.modifiedBy = modifiedBy
        this.slug = slug
        this.title = title
        this.subtitle = subtitle
        this.filename = filename
        this.listingImage = listingImage
        this.image = image
        this.confirmationMailingGroupId = confirmationMailingGroupId
        this.mailingGroupId = mailingGroupId
        this.priceRegular = priceRegular
        this.priceDiscounted = priceDiscounted
        resetChangedOnNotNull()
    }
}
