/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables.records


import java.time.Instant

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import org.xbery.artbeams.jooq.schema.tables.SearchIndex


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SearchIndexRecord() : UpdatableRecordImpl<SearchIndexRecord>(SearchIndex.SEARCH_INDEX) {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var entityType: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var entityId: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var title: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var description: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var keywords: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var slug: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var searchVector: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var metadata: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    open var validFrom: Instant?
        set(value): Unit = set(9, value)
        get(): Instant? = get(9) as Instant?

    open var validTo: Instant?
        set(value): Unit = set(10, value)
        get(): Instant? = get(10) as Instant?

    open var created: Instant?
        set(value): Unit = set(11, value)
        get(): Instant? = get(11) as Instant?

    open var modified: Instant?
        set(value): Unit = set(12, value)
        get(): Instant? = get(12) as Instant?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised SearchIndexRecord
     */
    constructor(id: String? = null, entityType: String? = null, entityId: String? = null, title: String? = null, description: String? = null, keywords: String? = null, slug: String? = null, searchVector: String? = null, metadata: String? = null, validFrom: Instant? = null, validTo: Instant? = null, created: Instant? = null, modified: Instant? = null): this() {
        this.id = id
        this.entityType = entityType
        this.entityId = entityId
        this.title = title
        this.description = description
        this.keywords = keywords
        this.slug = slug
        this.searchVector = searchVector
        this.metadata = metadata
        this.validFrom = validFrom
        this.validTo = validTo
        this.created = created
        this.modified = modified
        resetChangedOnNotNull()
    }
}
