/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import org.xbery.artbeams.jooq.schema.tables.Sequences


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SequencesRecord() : UpdatableRecordImpl<SequencesRecord>(Sequences.SEQUENCES) {

    open var sequenceName: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var nextValue: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised SequencesRecord
     */
    constructor(sequenceName: String? = null, nextValue: Long? = null): this() {
        this.sequenceName = sequenceName
        this.nextValue = nextValue
        resetChangedOnNotNull()
    }
}
