/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables.records


import java.time.Instant

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import org.xbery.artbeams.jooq.schema.tables.SystemEventLog


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SystemEventLogRecord() : UpdatableRecordImpl<SystemEventLogRecord>(SystemEventLog.SYSTEM_EVENT_LOG) {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var eventTime: Instant?
        set(value): Unit = set(1, value)
        get(): Instant? = get(1) as Instant?

    open var severity: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var eventType: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var origin: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var message: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var details: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var stackTrace: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var entityType: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    open var entityId: String?
        set(value): Unit = set(9, value)
        get(): String? = get(9) as String?

    open var userId: String?
        set(value): Unit = set(10, value)
        get(): String? = get(10) as String?

    open var ipAddress: String?
        set(value): Unit = set(11, value)
        get(): String? = get(11) as String?

    open var userAgent: String?
        set(value): Unit = set(12, value)
        get(): String? = get(12) as String?

    open var correlationId: String?
        set(value): Unit = set(13, value)
        get(): String? = get(13) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised SystemEventLogRecord
     */
    constructor(id: String? = null, eventTime: Instant? = null, severity: String? = null, eventType: String? = null, origin: String? = null, message: String? = null, details: String? = null, stackTrace: String? = null, entityType: String? = null, entityId: String? = null, userId: String? = null, ipAddress: String? = null, userAgent: String? = null, correlationId: String? = null): this() {
        this.id = id
        this.eventTime = eventTime
        this.severity = severity
        this.eventType = eventType
        this.origin = origin
        this.message = message
        this.details = details
        this.stackTrace = stackTrace
        this.entityType = entityType
        this.entityId = entityId
        this.userId = userId
        this.ipAddress = ipAddress
        this.userAgent = userAgent
        this.correlationId = correlationId
        resetChangedOnNotNull()
    }
}
