/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables.records


import org.jooq.impl.TableRecordImpl
import org.xbery.artbeams.jooq.schema.tables.UserRole


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UserRoleRecord() : TableRecordImpl<UserRoleRecord>(UserRole.USER_ROLE) {

    open var userId: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var roleId: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    /**
     * Create a detached, initialised UserRoleRecord
     */
    constructor(userId: String? = null, roleId: String? = null): this() {
        this.userId = userId
        this.roleId = roleId
        resetChangedOnNotNull()
    }
}
