/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables.records


import java.time.Instant

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import org.xbery.artbeams.jooq.schema.tables.UserProduct


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UserProductRecord() : UpdatableRecordImpl<UserProductRecord>(UserProduct.USER_PRODUCT) {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var userId: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var productId: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var created: Instant?
        set(value): Unit = set(3, value)
        get(): Instant? = get(3) as Instant?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised UserProductRecord
     */
    constructor(id: String? = null, userId: String? = null, productId: String? = null, created: Instant? = null): this() {
        this.id = id
        this.userId = userId
        this.productId = productId
        this.created = created
        resetChangedOnNotNull()
    }
}
