/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables.records


import java.time.Instant

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import org.xbery.artbeams.jooq.schema.tables.UserActivityLog


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UserActivityLogRecord() : UpdatableRecordImpl<UserActivityLogRecord>(UserActivityLog.USER_ACTIVITY_LOG) {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var userId: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var actionType: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var actionTime: Instant?
        set(value): Unit = set(3, value)
        get(): Instant? = get(3) as Instant?

    open var entityType: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var entityId: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var ipAddress: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var userAgent: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var details: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised UserActivityLogRecord
     */
    constructor(id: String? = null, userId: String? = null, actionType: String? = null, actionTime: Instant? = null, entityType: String? = null, entityId: String? = null, ipAddress: String? = null, userAgent: String? = null, details: String? = null): this() {
        this.id = id
        this.userId = userId
        this.actionType = actionType
        this.actionTime = actionTime
        this.entityType = entityType
        this.entityId = entityId
        this.ipAddress = ipAddress
        this.userAgent = userAgent
        this.details = details
        resetChangedOnNotNull()
    }
}
