package org.xbery.artbeams.courses.repository

import org.jooq.DSLContext
import org.jooq.Field
import org.jooq.RecordMapper
import org.jooq.RecordUnmapper
import org.jooq.Table
import org.springframework.stereotype.Repository
import org.xbery.artbeams.common.assets.repository.AssetRepository
import org.xbery.artbeams.courses.domain.Course
import org.xbery.artbeams.courses.repository.ModuleRepository
import org.xbery.artbeams.jooq.schema.tables.Courses
import org.xbery.artbeams.jooq.schema.tables.records.CoursesRecord
import org.xbery.artbeams.jooq.schema.tables.references.PRODUCT_COURSE

/**
 * Course repository.
 *
 * Note: A proper JOOQ table/record for courses should be generated via
 * src/main/resources/sql/create_tables.sql and jOOQ codegen. This implementation
 * uses lightweight jOOQ stubs included in the source tree to allow compilation
 * and tests to run before DB migrations are applied. Once migrations are added,
 * regenerate jOOQ classes and remove these stubs.
 */
@Repository
class CourseRepository(
    override val dsl: DSLContext,
    override val mapper: RecordMapper<CoursesRecord, Course>,
    override val unmapper: RecordUnmapper<Course, CoursesRecord>,
    private val moduleRepository: ModuleRepository
) : AssetRepository<Course, CoursesRecord>(
        dsl,
        mapper,
        unmapper
    ) {
    // Table reference for courses. Generated via jOOQ when SQL schema includes
    // courses and course_modules tables (see src/main/resources/sql/create_tables.sql).
    // NOTE: This file assumes jOOQ-generated classes CoursesRecord and COURSES
    // will exist after running migrations and code generation. For now the
    // repository compiles against lightweight jOOQ stubs that are included in
    // the source tree under src/main/kotlin/org/xbery/artbeams/jooq/schema.
    // These stubs are temporary and MUST be removed once DB migrations are
    // applied and real jOOQ classes are generated, otherwise they will clash
    // with the code generated by jOOQ.
    override val table: Table<CoursesRecord> = Courses.COURSES
    override val idField: Field<String?> = Courses.COURSES.ID

    // Populate modules for courses using ModuleRepository.
    // The ModuleRepository is a lightweight stub until DB migrations are
    // available and a proper JOOQ implementation replaces it.
    override fun findById(id: String): Course? {
        val course = super.findById(id) ?: return null
        return course.copy(modules = moduleRepository.findByCourseId(course.id))
    }

    override fun findAll(): List<Course> =
        super.findAll().map { course ->
            course.copy(modules = moduleRepository.findByCourseId(course.id))
        }

    /**
     * Returns courses assigned to the given product.
     */
    fun findCoursesForProduct(productId: String): List<Course> {
        // Select courses that are assigned to the given product via product_course join
        val courseIds = dsl
            .select(PRODUCT_COURSE.COURSE_ID)
            .from(PRODUCT_COURSE)
            .where(PRODUCT_COURSE.PRODUCT_ID.eq(productId))
            .fetch { rec -> requireNotNull(rec[PRODUCT_COURSE.COURSE_ID]) }

        if (courseIds.isEmpty()) return emptyList()

        return dsl
            .selectFrom(Courses.COURSES)
            .where(Courses.COURSES.ID.`in`(courseIds))
            .fetch(mapper)
            .map { c -> c.copy(modules = moduleRepository.findByCourseId(c.id)) }
    }

    /**
     * Persist product assignments for a given course. Previous assignments are replaced.
     */
    fun saveProductCourseAssignments(courseId: String, productIds: List<String>) {
        // Use transaction to ensure delete + inserts are atomic
        dsl.transaction { config ->
            val ctx = config.dsl()
            // Delete existing assignments for course
            ctx.deleteFrom(PRODUCT_COURSE).where(PRODUCT_COURSE.COURSE_ID.eq(courseId)).execute()
            // Insert new assignments
            productIds.filter { it.isNotBlank() }.forEach { pid ->
                ctx
                    .insertInto(PRODUCT_COURSE)
                    .set(PRODUCT_COURSE.PRODUCT_ID, pid)
                    .set(PRODUCT_COURSE.COURSE_ID, courseId)
                    .execute()
            }
        }
    }

    /**
     * Returns product ids assigned to a course.
     */
    fun findProductIdsForCourse(courseId: String): List<String> = dsl
        .select(PRODUCT_COURSE.PRODUCT_ID)
        .from(PRODUCT_COURSE)
        .where(PRODUCT_COURSE.COURSE_ID.eq(courseId))
        .fetch { record -> requireNotNull(record[PRODUCT_COURSE.PRODUCT_ID]) }
}
