/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables


import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.xbery.artbeams.jooq.schema.DefaultSchema
import org.xbery.artbeams.jooq.schema.keys.CONSTRAINT_2
import org.xbery.artbeams.jooq.schema.tables.records.AntispamQuizRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AntispamQuiz(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, AntispamQuizRecord>?,
    aliased: Table<AntispamQuizRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<AntispamQuizRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>antispam_quiz</code>
         */
        val ANTISPAM_QUIZ: AntispamQuiz = AntispamQuiz()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<AntispamQuizRecord> = AntispamQuizRecord::class.java

    /**
     * The column <code>antispam_quiz.question</code>.
     */
    val QUESTION: TableField<AntispamQuizRecord, String?> = createField(DSL.name("question"), SQLDataType.VARCHAR(128).nullable(false), this, "")

    /**
     * The column <code>antispam_quiz.answer</code>.
     */
    val ANSWER: TableField<AntispamQuizRecord, String?> = createField(DSL.name("answer"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<AntispamQuizRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<AntispamQuizRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>antispam_quiz</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>antispam_quiz</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>antispam_quiz</code> table reference
     */
    constructor(): this(DSL.name("antispam_quiz"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, AntispamQuizRecord>): this(Internal.createPathAlias(child, key), child, key, ANTISPAM_QUIZ, null)
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getPrimaryKey(): UniqueKey<AntispamQuizRecord> = CONSTRAINT_2
    override fun `as`(alias: String): AntispamQuiz = AntispamQuiz(DSL.name(alias), this)
    override fun `as`(alias: Name): AntispamQuiz = AntispamQuiz(alias, this)
    override fun `as`(alias: Table<*>): AntispamQuiz = AntispamQuiz(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): AntispamQuiz = AntispamQuiz(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): AntispamQuiz = AntispamQuiz(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): AntispamQuiz = AntispamQuiz(name.getQualifiedName(), null)
}
