/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables


import java.time.Instant

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.xbery.artbeams.common.persistence.jooq.converter.InstantConverter
import org.xbery.artbeams.jooq.schema.DefaultSchema
import org.xbery.artbeams.jooq.schema.keys.CONSTRAINT_B
import org.xbery.artbeams.jooq.schema.tables.records.ArticlesRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Articles(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, ArticlesRecord>?,
    aliased: Table<ArticlesRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<ArticlesRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>articles</code>
         */
        val ARTICLES: Articles = Articles()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ArticlesRecord> = ArticlesRecord::class.java

    /**
     * The column <code>articles.id</code>.
     */
    val ID: TableField<ArticlesRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>articles.external_id</code>.
     */
    val EXTERNAL_ID: TableField<ArticlesRecord, String?> = createField(DSL.name("external_id"), SQLDataType.VARCHAR(64).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>articles.valid_from</code>.
     */
    val VALID_FROM: TableField<ArticlesRecord, Instant?> = createField(DSL.name("valid_from"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "", InstantConverter())

    /**
     * The column <code>articles.valid_to</code>.
     */
    val VALID_TO: TableField<ArticlesRecord, Instant?> = createField(DSL.name("valid_to"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "", InstantConverter())

    /**
     * The column <code>articles.created</code>.
     */
    val CREATED: TableField<ArticlesRecord, Instant?> = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "", InstantConverter())

    /**
     * The column <code>articles.created_by</code>.
     */
    val CREATED_BY: TableField<ArticlesRecord, String?> = createField(DSL.name("created_by"), SQLDataType.VARCHAR(40).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>articles.modified</code>.
     */
    val MODIFIED: TableField<ArticlesRecord, Instant?> = createField(DSL.name("modified"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "", InstantConverter())

    /**
     * The column <code>articles.modified_by</code>.
     */
    val MODIFIED_BY: TableField<ArticlesRecord, String?> = createField(DSL.name("modified_by"), SQLDataType.VARCHAR(40).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>articles.slug</code>.
     */
    val SLUG: TableField<ArticlesRecord, String?> = createField(DSL.name("slug"), SQLDataType.VARCHAR(128).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>articles.title</code>.
     */
    val TITLE: TableField<ArticlesRecord, String?> = createField(DSL.name("title"), SQLDataType.VARCHAR(128).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>articles.image</code>.
     */
    val IMAGE: TableField<ArticlesRecord, String?> = createField(DSL.name("image"), SQLDataType.VARCHAR(128).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>articles.perex</code>.
     */
    val PEREX: TableField<ArticlesRecord, String?> = createField(DSL.name("perex"), SQLDataType.VARCHAR(4000).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>articles.body</code>.
     */
    val BODY: TableField<ArticlesRecord, String?> = createField(DSL.name("body"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>articles.body_edited</code>.
     */
    val BODY_EDITED: TableField<ArticlesRecord, String?> = createField(DSL.name("body_edited"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>articles.editor</code>.
     */
    val EDITOR: TableField<ArticlesRecord, String?> = createField(DSL.name("editor"), SQLDataType.VARCHAR(16).defaultValue(DSL.field(DSL.raw("'markdown'"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>articles.keywords</code>.
     */
    val KEYWORDS: TableField<ArticlesRecord, String?> = createField(DSL.name("keywords"), SQLDataType.VARCHAR(256).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>articles.show_on_blog</code>.
     */
    val SHOW_ON_BLOG: TableField<ArticlesRecord, Boolean?> = createField(DSL.name("show_on_blog"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("TRUE"), SQLDataType.BOOLEAN)), this, "")

    private constructor(alias: Name, aliased: Table<ArticlesRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<ArticlesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>articles</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>articles</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>articles</code> table reference
     */
    constructor(): this(DSL.name("articles"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, ArticlesRecord>): this(Internal.createPathAlias(child, key), child, key, ARTICLES, null)
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getPrimaryKey(): UniqueKey<ArticlesRecord> = CONSTRAINT_B
    override fun `as`(alias: String): Articles = Articles(DSL.name(alias), this)
    override fun `as`(alias: Name): Articles = Articles(alias, this)
    override fun `as`(alias: Table<*>): Articles = Articles(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Articles = Articles(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Articles = Articles(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Articles = Articles(name.getQualifiedName(), null)
}
