/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables


import kotlinx.datetime.Instant

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.xbery.artbeams.common.persistence.jooq.converter.InstantConverter
import org.xbery.artbeams.jooq.schema.DefaultSchema
import org.xbery.artbeams.jooq.schema.keys.CONSTRAINT_4
import org.xbery.artbeams.jooq.schema.tables.records.CategoriesRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Categories(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, CategoriesRecord>?,
    aliased: Table<CategoriesRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<CategoriesRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>categories</code>
         */
        val CATEGORIES: Categories = Categories()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CategoriesRecord> = CategoriesRecord::class.java

    /**
     * The column <code>categories.id</code>.
     */
    val ID: TableField<CategoriesRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>categories.valid_from</code>.
     */
    val VALID_FROM: TableField<CategoriesRecord, Instant?> = createField(DSL.name("valid_from"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "", InstantConverter())

    /**
     * The column <code>categories.valid_to</code>.
     */
    val VALID_TO: TableField<CategoriesRecord, Instant?> = createField(DSL.name("valid_to"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "", InstantConverter())

    /**
     * The column <code>categories.created</code>.
     */
    val CREATED: TableField<CategoriesRecord, Instant?> = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "", InstantConverter())

    /**
     * The column <code>categories.created_by</code>.
     */
    val CREATED_BY: TableField<CategoriesRecord, String?> = createField(DSL.name("created_by"), SQLDataType.VARCHAR(40).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>categories.modified</code>.
     */
    val MODIFIED: TableField<CategoriesRecord, Instant?> = createField(DSL.name("modified"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "", InstantConverter())

    /**
     * The column <code>categories.modified_by</code>.
     */
    val MODIFIED_BY: TableField<CategoriesRecord, String?> = createField(DSL.name("modified_by"), SQLDataType.VARCHAR(40).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>categories.slug</code>.
     */
    val SLUG: TableField<CategoriesRecord, String?> = createField(DSL.name("slug"), SQLDataType.VARCHAR(128).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>categories.title</code>.
     */
    val TITLE: TableField<CategoriesRecord, String?> = createField(DSL.name("title"), SQLDataType.VARCHAR(128).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>categories.description</code>.
     */
    val DESCRIPTION: TableField<CategoriesRecord, String?> = createField(DSL.name("description"), SQLDataType.VARCHAR(1000).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    private constructor(alias: Name, aliased: Table<CategoriesRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<CategoriesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>categories</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>categories</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>categories</code> table reference
     */
    constructor(): this(DSL.name("categories"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, CategoriesRecord>): this(Internal.createPathAlias(child, key), child, key, CATEGORIES, null)
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getPrimaryKey(): UniqueKey<CategoriesRecord> = CONSTRAINT_4
    override fun `as`(alias: String): Categories = Categories(DSL.name(alias), this)
    override fun `as`(alias: Name): Categories = Categories(alias, this)
    override fun `as`(alias: Table<*>): Categories = Categories(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Categories = Categories(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Categories = Categories(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Categories = Categories(name.getQualifiedName(), null)
}
