/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables


import java.time.Instant

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.xbery.artbeams.common.persistence.jooq.converter.InstantConverter
import org.xbery.artbeams.jooq.schema.DefaultSchema
import org.xbery.artbeams.jooq.schema.indexes.IDX_COMMENTS_ENTITY_ID
import org.xbery.artbeams.jooq.schema.indexes.IDX_COMMENTS_STATE
import org.xbery.artbeams.jooq.schema.keys.CONSTRAINT_DC
import org.xbery.artbeams.jooq.schema.keys.PARENT_ID_FK
import org.xbery.artbeams.jooq.schema.tables.Comments.CommentsPath
import org.xbery.artbeams.jooq.schema.tables.records.CommentsRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Comments(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CommentsRecord>?,
    parentPath: InverseForeignKey<out Record, CommentsRecord>?,
    aliased: Table<CommentsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CommentsRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>comments</code>
         */
        val COMMENTS: Comments = Comments()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CommentsRecord> = CommentsRecord::class.java

    /**
     * The column <code>comments.id</code>.
     */
    val ID: TableField<CommentsRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>comments.parent_id</code>.
     */
    val PARENT_ID: TableField<CommentsRecord, String?> = createField(DSL.name("parent_id"), SQLDataType.VARCHAR(40).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>comments.created</code>.
     */
    val CREATED: TableField<CommentsRecord, Instant?> = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "", InstantConverter())

    /**
     * The column <code>comments.created_by</code>.
     */
    val CREATED_BY: TableField<CommentsRecord, String?> = createField(DSL.name("created_by"), SQLDataType.VARCHAR(40).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>comments.modified</code>.
     */
    val MODIFIED: TableField<CommentsRecord, Instant?> = createField(DSL.name("modified"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "", InstantConverter())

    /**
     * The column <code>comments.modified_by</code>.
     */
    val MODIFIED_BY: TableField<CommentsRecord, String?> = createField(DSL.name("modified_by"), SQLDataType.VARCHAR(40).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>comments.state</code>.
     */
    val STATE: TableField<CommentsRecord, String?> = createField(DSL.name("state"), SQLDataType.VARCHAR(20).nullable(false).defaultValue(DSL.field(DSL.raw("'WAITING_FOR_APPROVAL'"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>comments.comment</code>.
     */
    val COMMENT: TableField<CommentsRecord, String?> = createField(DSL.name("comment"), SQLDataType.VARCHAR(20000).nullable(false), this, "")

    /**
     * The column <code>comments.username</code>.
     */
    val USERNAME: TableField<CommentsRecord, String?> = createField(DSL.name("username"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>comments.email</code>.
     */
    val EMAIL: TableField<CommentsRecord, String?> = createField(DSL.name("email"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>comments.entity_type</code>.
     */
    val ENTITY_TYPE: TableField<CommentsRecord, String?> = createField(DSL.name("entity_type"), SQLDataType.VARCHAR(20).nullable(false), this, "")

    /**
     * The column <code>comments.entity_id</code>.
     */
    val ENTITY_ID: TableField<CommentsRecord, String?> = createField(DSL.name("entity_id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>comments.ip</code>.
     */
    val IP: TableField<CommentsRecord, String?> = createField(DSL.name("ip"), SQLDataType.VARCHAR(60).nullable(false), this, "")

    /**
     * The column <code>comments.user_agent</code>.
     */
    val USER_AGENT: TableField<CommentsRecord, String?> = createField(DSL.name("user_agent"), SQLDataType.VARCHAR(200).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<CommentsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CommentsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CommentsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>comments</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>comments</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>comments</code> table reference
     */
    constructor(): this(DSL.name("comments"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CommentsRecord>?, parentPath: InverseForeignKey<out Record, CommentsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, COMMENTS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class CommentsPath : Comments, Path<CommentsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CommentsRecord>?, parentPath: InverseForeignKey<out Record, CommentsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<CommentsRecord>): super(alias, aliased)
        override fun `as`(alias: String): CommentsPath = CommentsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): CommentsPath = CommentsPath(alias, this)
        override fun `as`(alias: Table<*>): CommentsPath = CommentsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getIndexes(): List<Index> = listOf(IDX_COMMENTS_ENTITY_ID, IDX_COMMENTS_STATE)
    override fun getPrimaryKey(): UniqueKey<CommentsRecord> = CONSTRAINT_DC
    override fun getReferences(): List<ForeignKey<CommentsRecord, *>> = listOf(PARENT_ID_FK)

    private lateinit var _comments: CommentsPath

    /**
     * Get the implicit join path to the <code>PUBLIC.comments</code> table.
     */
    fun comments(): CommentsPath {
        if (!this::_comments.isInitialized)
            _comments = CommentsPath(this, PARENT_ID_FK, null)

        return _comments;
    }

    val comments: CommentsPath
        get(): CommentsPath = comments()
    override fun `as`(alias: String): Comments = Comments(DSL.name(alias), this)
    override fun `as`(alias: Name): Comments = Comments(alias, this)
    override fun `as`(alias: Table<*>): Comments = Comments(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Comments = Comments(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Comments = Comments(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Comments = Comments(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Comments = Comments(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Comments = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Comments = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Comments = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Comments = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Comments = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Comments = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Comments = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Comments = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Comments = where(DSL.notExists(select))
}
