/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables


import java.time.Instant

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.xbery.artbeams.common.persistence.jooq.converter.InstantConverter
import org.xbery.artbeams.jooq.schema.DefaultSchema
import org.xbery.artbeams.jooq.schema.indexes.IDX_CONSENTS_LOGIN
import org.xbery.artbeams.jooq.schema.indexes.IDX_CONSENTS_LOGIN_TYPE_VALIDITY
import org.xbery.artbeams.jooq.schema.indexes.IDX_CONSENTS_VALIDITY
import org.xbery.artbeams.jooq.schema.keys.CONSTRAINT_DE
import org.xbery.artbeams.jooq.schema.tables.records.ConsentsRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Consents(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ConsentsRecord>?,
    parentPath: InverseForeignKey<out Record, ConsentsRecord>?,
    aliased: Table<ConsentsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<ConsentsRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>consents</code>
         */
        val CONSENTS: Consents = Consents()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ConsentsRecord> = ConsentsRecord::class.java

    /**
     * The column <code>consents.id</code>.
     */
    val ID: TableField<ConsentsRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>consents.valid_from</code>.
     */
    val VALID_FROM: TableField<ConsentsRecord, Instant?> = createField(DSL.name("valid_from"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "", InstantConverter())

    /**
     * The column <code>consents.valid_to</code>.
     */
    val VALID_TO: TableField<ConsentsRecord, Instant?> = createField(DSL.name("valid_to"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "", InstantConverter())

    /**
     * The column <code>consents.login</code>.
     */
    val LOGIN: TableField<ConsentsRecord, String?> = createField(DSL.name("login"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>consents.consent_type</code>.
     */
    val CONSENT_TYPE: TableField<ConsentsRecord, String?> = createField(DSL.name("consent_type"), SQLDataType.VARCHAR(20).nullable(false), this, "")

    /**
     * The column <code>consents.origin_product_id</code>.
     */
    val ORIGIN_PRODUCT_ID: TableField<ConsentsRecord, String?> = createField(DSL.name("origin_product_id"), SQLDataType.VARCHAR(40), this, "")

    private constructor(alias: Name, aliased: Table<ConsentsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<ConsentsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<ConsentsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>consents</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>consents</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>consents</code> table reference
     */
    constructor(): this(DSL.name("consents"), null)
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getIndexes(): List<Index> = listOf(IDX_CONSENTS_LOGIN, IDX_CONSENTS_LOGIN_TYPE_VALIDITY, IDX_CONSENTS_VALIDITY)
    override fun getPrimaryKey(): UniqueKey<ConsentsRecord> = CONSTRAINT_DE
    override fun `as`(alias: String): Consents = Consents(DSL.name(alias), this)
    override fun `as`(alias: Name): Consents = Consents(alias, this)
    override fun `as`(alias: Table<*>): Consents = Consents(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Consents = Consents(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Consents = Consents(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Consents = Consents(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Consents = Consents(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Consents = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Consents = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Consents = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Consents = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Consents = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Consents = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Consents = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Consents = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Consents = where(DSL.notExists(select))
}
