/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables


import java.time.Instant

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.xbery.artbeams.common.persistence.jooq.converter.InstantConverter
import org.xbery.artbeams.jooq.schema.DefaultSchema
import org.xbery.artbeams.jooq.schema.indexes.IDX_CONSENTS_LOGIN
import org.xbery.artbeams.jooq.schema.indexes.IDX_CONSENTS_LOGIN_TYPE_VALIDITY
import org.xbery.artbeams.jooq.schema.indexes.IDX_CONSENTS_VALIDITY
import org.xbery.artbeams.jooq.schema.keys.CONSTRAINT_DE
import org.xbery.artbeams.jooq.schema.tables.records.ConsentsRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Consents(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, ConsentsRecord>?,
    aliased: Table<ConsentsRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<ConsentsRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>consents</code>
         */
        val CONSENTS: Consents = Consents()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ConsentsRecord> = ConsentsRecord::class.java

    /**
     * The column <code>consents.id</code>.
     */
    val ID: TableField<ConsentsRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>consents.valid_from</code>.
     */
    val VALID_FROM: TableField<ConsentsRecord, Instant?> = createField(DSL.name("valid_from"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "", InstantConverter())

    /**
     * The column <code>consents.valid_to</code>.
     */
    val VALID_TO: TableField<ConsentsRecord, Instant?> = createField(DSL.name("valid_to"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "", InstantConverter())

    /**
     * The column <code>consents.login</code>.
     */
    val LOGIN: TableField<ConsentsRecord, String?> = createField(DSL.name("login"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>consents.consent_type</code>.
     */
    val CONSENT_TYPE: TableField<ConsentsRecord, String?> = createField(DSL.name("consent_type"), SQLDataType.VARCHAR(20).nullable(false), this, "")

    /**
     * The column <code>consents.origin_product_id</code>.
     */
    val ORIGIN_PRODUCT_ID: TableField<ConsentsRecord, String?> = createField(DSL.name("origin_product_id"), SQLDataType.VARCHAR(40), this, "")

    private constructor(alias: Name, aliased: Table<ConsentsRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<ConsentsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>consents</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>consents</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>consents</code> table reference
     */
    constructor(): this(DSL.name("consents"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, ConsentsRecord>): this(Internal.createPathAlias(child, key), child, key, CONSENTS, null)
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getIndexes(): List<Index> = listOf(IDX_CONSENTS_LOGIN, IDX_CONSENTS_LOGIN_TYPE_VALIDITY, IDX_CONSENTS_VALIDITY)
    override fun getPrimaryKey(): UniqueKey<ConsentsRecord> = CONSTRAINT_DE
    override fun `as`(alias: String): Consents = Consents(DSL.name(alias), this)
    override fun `as`(alias: Name): Consents = Consents(alias, this)
    override fun `as`(alias: Table<*>): Consents = Consents(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Consents = Consents(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Consents = Consents(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Consents = Consents(name.getQualifiedName(), null)
}
