/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables


import java.time.Instant

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.xbery.artbeams.common.persistence.jooq.converter.InstantConverter
import org.xbery.artbeams.jooq.schema.DefaultSchema
import org.xbery.artbeams.jooq.schema.keys.CONSTRAINT_3
import org.xbery.artbeams.jooq.schema.keys.FK_COURSE_MODULES_COURSE_ID
import org.xbery.artbeams.jooq.schema.tables.CourseModules.CourseModulesPath
import org.xbery.artbeams.jooq.schema.tables.records.CoursesRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Courses(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CoursesRecord>?,
    parentPath: InverseForeignKey<out Record, CoursesRecord>?,
    aliased: Table<CoursesRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CoursesRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>courses</code>
         */
        val COURSES: Courses = Courses()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CoursesRecord> = CoursesRecord::class.java

    /**
     * The column <code>courses.id</code>.
     */
    val ID: TableField<CoursesRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>courses.created</code>.
     */
    val CREATED: TableField<CoursesRecord, Instant?> = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "", InstantConverter())

    /**
     * The column <code>courses.created_by</code>.
     */
    val CREATED_BY: TableField<CoursesRecord, String?> = createField(DSL.name("created_by"), SQLDataType.VARCHAR(40).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>courses.modified</code>.
     */
    val MODIFIED: TableField<CoursesRecord, Instant?> = createField(DSL.name("modified"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "", InstantConverter())

    /**
     * The column <code>courses.modified_by</code>.
     */
    val MODIFIED_BY: TableField<CoursesRecord, String?> = createField(DSL.name("modified_by"), SQLDataType.VARCHAR(40).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>courses.slug</code>.
     */
    val SLUG: TableField<CoursesRecord, String?> = createField(DSL.name("slug"), SQLDataType.VARCHAR(128).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>courses.title</code>.
     */
    val TITLE: TableField<CoursesRecord, String?> = createField(DSL.name("title"), SQLDataType.VARCHAR(128).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>courses.subtitle</code>.
     */
    val SUBTITLE: TableField<CoursesRecord, String?> = createField(DSL.name("subtitle"), SQLDataType.VARCHAR(256).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>courses.listing_image</code>.
     */
    val LISTING_IMAGE: TableField<CoursesRecord, String?> = createField(DSL.name("listing_image"), SQLDataType.VARCHAR(128).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>courses.image</code>.
     */
    val IMAGE: TableField<CoursesRecord, String?> = createField(DSL.name("image"), SQLDataType.VARCHAR(128).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>courses.perex</code>.
     */
    val PEREX: TableField<CoursesRecord, String?> = createField(DSL.name("perex"), SQLDataType.VARCHAR(4000).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    private constructor(alias: Name, aliased: Table<CoursesRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CoursesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CoursesRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>courses</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>courses</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>courses</code> table reference
     */
    constructor(): this(DSL.name("courses"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CoursesRecord>?, parentPath: InverseForeignKey<out Record, CoursesRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, COURSES, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class CoursesPath : Courses, Path<CoursesRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CoursesRecord>?, parentPath: InverseForeignKey<out Record, CoursesRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<CoursesRecord>): super(alias, aliased)
        override fun `as`(alias: String): CoursesPath = CoursesPath(DSL.name(alias), this)
        override fun `as`(alias: Name): CoursesPath = CoursesPath(alias, this)
        override fun `as`(alias: Table<*>): CoursesPath = CoursesPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getPrimaryKey(): UniqueKey<CoursesRecord> = CONSTRAINT_3

    private lateinit var _courseModules: CourseModulesPath

    /**
     * Get the implicit to-many join path to the
     * <code>PUBLIC.course_modules</code> table
     */
    fun courseModules(): CourseModulesPath {
        if (!this::_courseModules.isInitialized)
            _courseModules = CourseModulesPath(this, null, FK_COURSE_MODULES_COURSE_ID.inverseKey)

        return _courseModules;
    }

    val courseModules: CourseModulesPath
        get(): CourseModulesPath = courseModules()
    override fun `as`(alias: String): Courses = Courses(DSL.name(alias), this)
    override fun `as`(alias: Name): Courses = Courses(alias, this)
    override fun `as`(alias: Table<*>): Courses = Courses(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Courses = Courses(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Courses = Courses(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Courses = Courses(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Courses = Courses(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Courses = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Courses = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Courses = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Courses = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Courses = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Courses = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Courses = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Courses = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Courses = where(DSL.notExists(select))
}
