/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables


import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.xbery.artbeams.jooq.schema.DefaultSchema
import org.xbery.artbeams.jooq.schema.indexes.IDX_COURSE_MODULES_COURSE_ID
import org.xbery.artbeams.jooq.schema.keys.CONSTRAINT_A
import org.xbery.artbeams.jooq.schema.keys.FK_COURSE_MODULES_COURSE_ID
import org.xbery.artbeams.jooq.schema.tables.Courses.CoursesPath
import org.xbery.artbeams.jooq.schema.tables.records.CourseModulesRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CourseModules(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CourseModulesRecord>?,
    parentPath: InverseForeignKey<out Record, CourseModulesRecord>?,
    aliased: Table<CourseModulesRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CourseModulesRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>course_modules</code>
         */
        val COURSE_MODULES: CourseModules = CourseModules()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CourseModulesRecord> = CourseModulesRecord::class.java

    /**
     * The column <code>course_modules.id</code>.
     */
    val ID: TableField<CourseModulesRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>course_modules.course_id</code>.
     */
    val COURSE_ID: TableField<CourseModulesRecord, String?> = createField(DSL.name("course_id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>course_modules.title</code>.
     */
    val TITLE: TableField<CourseModulesRecord, String?> = createField(DSL.name("title"), SQLDataType.VARCHAR(128).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>course_modules.image</code>.
     */
    val IMAGE: TableField<CourseModulesRecord, String?> = createField(DSL.name("image"), SQLDataType.VARCHAR(128).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>course_modules.short_description</code>.
     */
    val SHORT_DESCRIPTION: TableField<CourseModulesRecord, String?> = createField(DSL.name("short_description"), SQLDataType.VARCHAR(1000).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>course_modules.perex</code>.
     */
    val PEREX: TableField<CourseModulesRecord, String?> = createField(DSL.name("perex"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "")

    /**
     * The column <code>course_modules.sort_order</code>.
     */
    val SORT_ORDER: TableField<CourseModulesRecord, Int?> = createField(DSL.name("sort_order"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "")

    private constructor(alias: Name, aliased: Table<CourseModulesRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CourseModulesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CourseModulesRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>course_modules</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>course_modules</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>course_modules</code> table reference
     */
    constructor(): this(DSL.name("course_modules"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CourseModulesRecord>?, parentPath: InverseForeignKey<out Record, CourseModulesRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, COURSE_MODULES, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class CourseModulesPath : CourseModules, Path<CourseModulesRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CourseModulesRecord>?, parentPath: InverseForeignKey<out Record, CourseModulesRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<CourseModulesRecord>): super(alias, aliased)
        override fun `as`(alias: String): CourseModulesPath = CourseModulesPath(DSL.name(alias), this)
        override fun `as`(alias: Name): CourseModulesPath = CourseModulesPath(alias, this)
        override fun `as`(alias: Table<*>): CourseModulesPath = CourseModulesPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getIndexes(): List<Index> = listOf(IDX_COURSE_MODULES_COURSE_ID)
    override fun getPrimaryKey(): UniqueKey<CourseModulesRecord> = CONSTRAINT_A
    override fun getReferences(): List<ForeignKey<CourseModulesRecord, *>> = listOf(FK_COURSE_MODULES_COURSE_ID)

    private lateinit var _courses: CoursesPath

    /**
     * Get the implicit join path to the <code>PUBLIC.courses</code> table.
     */
    fun courses(): CoursesPath {
        if (!this::_courses.isInitialized)
            _courses = CoursesPath(this, FK_COURSE_MODULES_COURSE_ID, null)

        return _courses;
    }

    val courses: CoursesPath
        get(): CoursesPath = courses()
    override fun `as`(alias: String): CourseModules = CourseModules(DSL.name(alias), this)
    override fun `as`(alias: Name): CourseModules = CourseModules(alias, this)
    override fun `as`(alias: Table<*>): CourseModules = CourseModules(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): CourseModules = CourseModules(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): CourseModules = CourseModules(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): CourseModules = CourseModules(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): CourseModules = CourseModules(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): CourseModules = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): CourseModules = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): CourseModules = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): CourseModules = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): CourseModules = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): CourseModules = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): CourseModules = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): CourseModules = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): CourseModules = where(DSL.notExists(select))
}
