/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables


import java.time.Instant

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.xbery.artbeams.common.persistence.jooq.converter.InstantConverter
import org.xbery.artbeams.jooq.schema.DefaultSchema
import org.xbery.artbeams.jooq.schema.indexes.IDX_FAQ_ENTRIES_ENTITY
import org.xbery.artbeams.jooq.schema.indexes.IDX_FAQ_ENTRIES_ENTITY_SORT
import org.xbery.artbeams.jooq.schema.keys.CONSTRAINT_8
import org.xbery.artbeams.jooq.schema.tables.records.FaqEntriesRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class FaqEntries(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, FaqEntriesRecord>?,
    parentPath: InverseForeignKey<out Record, FaqEntriesRecord>?,
    aliased: Table<FaqEntriesRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<FaqEntriesRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>faq_entries</code>
         */
        val FAQ_ENTRIES: FaqEntries = FaqEntries()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<FaqEntriesRecord> = FaqEntriesRecord::class.java

    /**
     * The column <code>faq_entries.id</code>.
     */
    val ID: TableField<FaqEntriesRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>faq_entries.created</code>.
     */
    val CREATED: TableField<FaqEntriesRecord, Instant?> = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "", InstantConverter())

    /**
     * The column <code>faq_entries.created_by</code>.
     */
    val CREATED_BY: TableField<FaqEntriesRecord, String?> = createField(DSL.name("created_by"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>faq_entries.modified</code>.
     */
    val MODIFIED: TableField<FaqEntriesRecord, Instant?> = createField(DSL.name("modified"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "", InstantConverter())

    /**
     * The column <code>faq_entries.modified_by</code>.
     */
    val MODIFIED_BY: TableField<FaqEntriesRecord, String?> = createField(DSL.name("modified_by"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>faq_entries.entity_type</code>.
     */
    val ENTITY_TYPE: TableField<FaqEntriesRecord, String?> = createField(DSL.name("entity_type"), SQLDataType.VARCHAR(20).nullable(false), this, "")

    /**
     * The column <code>faq_entries.entity_id</code>.
     */
    val ENTITY_ID: TableField<FaqEntriesRecord, String?> = createField(DSL.name("entity_id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>faq_entries.question</code>.
     */
    val QUESTION: TableField<FaqEntriesRecord, String?> = createField(DSL.name("question"), SQLDataType.VARCHAR(500).nullable(false), this, "")

    /**
     * The column <code>faq_entries.answer</code>.
     */
    val ANSWER: TableField<FaqEntriesRecord, String?> = createField(DSL.name("answer"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>faq_entries.sort_order</code>.
     */
    val SORT_ORDER: TableField<FaqEntriesRecord, Int?> = createField(DSL.name("sort_order"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "")

    private constructor(alias: Name, aliased: Table<FaqEntriesRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<FaqEntriesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<FaqEntriesRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>faq_entries</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>faq_entries</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>faq_entries</code> table reference
     */
    constructor(): this(DSL.name("faq_entries"), null)
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getIndexes(): List<Index> = listOf(IDX_FAQ_ENTRIES_ENTITY, IDX_FAQ_ENTRIES_ENTITY_SORT)
    override fun getPrimaryKey(): UniqueKey<FaqEntriesRecord> = CONSTRAINT_8
    override fun `as`(alias: String): FaqEntries = FaqEntries(DSL.name(alias), this)
    override fun `as`(alias: Name): FaqEntries = FaqEntries(alias, this)
    override fun `as`(alias: Table<*>): FaqEntries = FaqEntries(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): FaqEntries = FaqEntries(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): FaqEntries = FaqEntries(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): FaqEntries = FaqEntries(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): FaqEntries = FaqEntries(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): FaqEntries = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): FaqEntries = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): FaqEntries = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): FaqEntries = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): FaqEntries = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): FaqEntries = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): FaqEntries = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): FaqEntries = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): FaqEntries = where(DSL.notExists(select))
}
