/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables


import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.xbery.artbeams.jooq.schema.DefaultSchema
import org.xbery.artbeams.jooq.schema.keys.CONSTRAINT_C3A
import org.xbery.artbeams.jooq.schema.tables.records.LocalisationRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Localisation(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, LocalisationRecord>?,
    parentPath: InverseForeignKey<out Record, LocalisationRecord>?,
    aliased: Table<LocalisationRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<LocalisationRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>localisation</code>
         */
        val LOCALISATION: Localisation = Localisation()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<LocalisationRecord> = LocalisationRecord::class.java

    /**
     * The column <code>localisation.entry_key</code>.
     */
    val ENTRY_KEY: TableField<LocalisationRecord, String?> = createField(DSL.name("entry_key"), SQLDataType.VARCHAR(120).nullable(false), this, "")

    /**
     * The column <code>localisation.entry_value</code>.
     */
    val ENTRY_VALUE: TableField<LocalisationRecord, String?> = createField(DSL.name("entry_value"), SQLDataType.VARCHAR(1000).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<LocalisationRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<LocalisationRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<LocalisationRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>localisation</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>localisation</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>localisation</code> table reference
     */
    constructor(): this(DSL.name("localisation"), null)
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getPrimaryKey(): UniqueKey<LocalisationRecord> = CONSTRAINT_C3A
    override fun `as`(alias: String): Localisation = Localisation(DSL.name(alias), this)
    override fun `as`(alias: Name): Localisation = Localisation(alias, this)
    override fun `as`(alias: Table<*>): Localisation = Localisation(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Localisation = Localisation(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Localisation = Localisation(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Localisation = Localisation(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Localisation = Localisation(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Localisation = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Localisation = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Localisation = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Localisation = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Localisation = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Localisation = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Localisation = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Localisation = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Localisation = where(DSL.notExists(select))
}
