/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables


import java.time.Instant

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.xbery.artbeams.common.persistence.jooq.converter.InstantConverter
import org.xbery.artbeams.jooq.schema.DefaultSchema
import org.xbery.artbeams.jooq.schema.indexes.IDX_NEWS_SUBSCRIPTION_EMAIL
import org.xbery.artbeams.jooq.schema.keys.CONSTRAINT_7A
import org.xbery.artbeams.jooq.schema.tables.records.NewsSubscriptionRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class NewsSubscription(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, NewsSubscriptionRecord>?,
    parentPath: InverseForeignKey<out Record, NewsSubscriptionRecord>?,
    aliased: Table<NewsSubscriptionRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<NewsSubscriptionRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>news_subscription</code>
         */
        val NEWS_SUBSCRIPTION: NewsSubscription = NewsSubscription()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<NewsSubscriptionRecord> = NewsSubscriptionRecord::class.java

    /**
     * The column <code>news_subscription.id</code>.
     */
    val ID: TableField<NewsSubscriptionRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>news_subscription.email</code>.
     */
    val EMAIL: TableField<NewsSubscriptionRecord, String?> = createField(DSL.name("email"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>news_subscription.created</code>.
     */
    val CREATED: TableField<NewsSubscriptionRecord, Instant?> = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "", InstantConverter())

    /**
     * The column <code>news_subscription.confirmed</code>.
     */
    val CONFIRMED: TableField<NewsSubscriptionRecord, Instant?> = createField(DSL.name("confirmed"), SQLDataType.LOCALDATETIME(6), this, "", InstantConverter())

    private constructor(alias: Name, aliased: Table<NewsSubscriptionRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<NewsSubscriptionRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<NewsSubscriptionRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>news_subscription</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>news_subscription</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>news_subscription</code> table reference
     */
    constructor(): this(DSL.name("news_subscription"), null)
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getIndexes(): List<Index> = listOf(IDX_NEWS_SUBSCRIPTION_EMAIL)
    override fun getPrimaryKey(): UniqueKey<NewsSubscriptionRecord> = CONSTRAINT_7A
    override fun `as`(alias: String): NewsSubscription = NewsSubscription(DSL.name(alias), this)
    override fun `as`(alias: Name): NewsSubscription = NewsSubscription(alias, this)
    override fun `as`(alias: Table<*>): NewsSubscription = NewsSubscription(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): NewsSubscription = NewsSubscription(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): NewsSubscription = NewsSubscription(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): NewsSubscription = NewsSubscription(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): NewsSubscription = NewsSubscription(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): NewsSubscription = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): NewsSubscription = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): NewsSubscription = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): NewsSubscription = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): NewsSubscription = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): NewsSubscription = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): NewsSubscription = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): NewsSubscription = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): NewsSubscription = where(DSL.notExists(select))
}
