/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables


import java.math.BigDecimal
import java.time.Instant

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.xbery.artbeams.common.persistence.jooq.converter.InstantConverter
import org.xbery.artbeams.jooq.schema.DefaultSchema
import org.xbery.artbeams.jooq.schema.keys.CONSTRAINT_7
import org.xbery.artbeams.jooq.schema.keys.ORDERED_PRODUCT_FK
import org.xbery.artbeams.jooq.schema.keys.ORDER_FK
import org.xbery.artbeams.jooq.schema.tables.Orders.OrdersPath
import org.xbery.artbeams.jooq.schema.tables.Products.ProductsPath
import org.xbery.artbeams.jooq.schema.tables.records.OrderItemsRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class OrderItems(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, OrderItemsRecord>?,
    parentPath: InverseForeignKey<out Record, OrderItemsRecord>?,
    aliased: Table<OrderItemsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<OrderItemsRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>order_items</code>
         */
        val ORDER_ITEMS: OrderItems = OrderItems()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<OrderItemsRecord> = OrderItemsRecord::class.java

    /**
     * The column <code>order_items.id</code>.
     */
    val ID: TableField<OrderItemsRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>order_items.created</code>.
     */
    val CREATED: TableField<OrderItemsRecord, Instant?> = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "", InstantConverter())

    /**
     * The column <code>order_items.created_by</code>.
     */
    val CREATED_BY: TableField<OrderItemsRecord, String?> = createField(DSL.name("created_by"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>order_items.modified</code>.
     */
    val MODIFIED: TableField<OrderItemsRecord, Instant?> = createField(DSL.name("modified"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "", InstantConverter())

    /**
     * The column <code>order_items.modified_by</code>.
     */
    val MODIFIED_BY: TableField<OrderItemsRecord, String?> = createField(DSL.name("modified_by"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>order_items.order_id</code>.
     */
    val ORDER_ID: TableField<OrderItemsRecord, String?> = createField(DSL.name("order_id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>order_items.product_id</code>.
     */
    val PRODUCT_ID: TableField<OrderItemsRecord, String?> = createField(DSL.name("product_id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>order_items.quantity</code>.
     */
    val QUANTITY: TableField<OrderItemsRecord, Int?> = createField(DSL.name("quantity"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>order_items.price</code>.
     */
    val PRICE: TableField<OrderItemsRecord, BigDecimal?> = createField(DSL.name("price"), SQLDataType.DECIMAL(19, 4).nullable(false), this, "")

    /**
     * The column <code>order_items.downloaded</code>.
     */
    val DOWNLOADED: TableField<OrderItemsRecord, Instant?> = createField(DSL.name("downloaded"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "", InstantConverter())

    private constructor(alias: Name, aliased: Table<OrderItemsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<OrderItemsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<OrderItemsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>order_items</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>order_items</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>order_items</code> table reference
     */
    constructor(): this(DSL.name("order_items"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, OrderItemsRecord>?, parentPath: InverseForeignKey<out Record, OrderItemsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, ORDER_ITEMS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class OrderItemsPath : OrderItems, Path<OrderItemsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, OrderItemsRecord>?, parentPath: InverseForeignKey<out Record, OrderItemsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<OrderItemsRecord>): super(alias, aliased)
        override fun `as`(alias: String): OrderItemsPath = OrderItemsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): OrderItemsPath = OrderItemsPath(alias, this)
        override fun `as`(alias: Table<*>): OrderItemsPath = OrderItemsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getPrimaryKey(): UniqueKey<OrderItemsRecord> = CONSTRAINT_7
    override fun getReferences(): List<ForeignKey<OrderItemsRecord, *>> = listOf(ORDER_FK, ORDERED_PRODUCT_FK)

    private lateinit var _orders: OrdersPath

    /**
     * Get the implicit join path to the <code>PUBLIC.orders</code> table.
     */
    fun orders(): OrdersPath {
        if (!this::_orders.isInitialized)
            _orders = OrdersPath(this, ORDER_FK, null)

        return _orders;
    }

    val orders: OrdersPath
        get(): OrdersPath = orders()

    private lateinit var _products: ProductsPath

    /**
     * Get the implicit join path to the <code>PUBLIC.products</code> table.
     */
    fun products(): ProductsPath {
        if (!this::_products.isInitialized)
            _products = ProductsPath(this, ORDERED_PRODUCT_FK, null)

        return _products;
    }

    val products: ProductsPath
        get(): ProductsPath = products()
    override fun `as`(alias: String): OrderItems = OrderItems(DSL.name(alias), this)
    override fun `as`(alias: Name): OrderItems = OrderItems(alias, this)
    override fun `as`(alias: Table<*>): OrderItems = OrderItems(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): OrderItems = OrderItems(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): OrderItems = OrderItems(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): OrderItems = OrderItems(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): OrderItems = OrderItems(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): OrderItems = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): OrderItems = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): OrderItems = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): OrderItems = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): OrderItems = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): OrderItems = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): OrderItems = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): OrderItems = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): OrderItems = where(DSL.notExists(select))
}
