/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables


import java.time.Instant

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.xbery.artbeams.common.persistence.jooq.converter.InstantConverter
import org.xbery.artbeams.jooq.schema.DefaultSchema
import org.xbery.artbeams.jooq.schema.indexes.IDX_ORDERS_ORDER_NUMBER
import org.xbery.artbeams.jooq.schema.keys.CONSTRAINT_C3
import org.xbery.artbeams.jooq.schema.keys.ORDER_FK
import org.xbery.artbeams.jooq.schema.tables.OrderItems.OrderItemsPath
import org.xbery.artbeams.jooq.schema.tables.records.OrdersRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Orders(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, OrdersRecord>?,
    parentPath: InverseForeignKey<out Record, OrdersRecord>?,
    aliased: Table<OrdersRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<OrdersRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>orders</code>
         */
        val ORDERS: Orders = Orders()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<OrdersRecord> = OrdersRecord::class.java

    /**
     * The column <code>orders.id</code>.
     */
    val ID: TableField<OrdersRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>orders.created</code>.
     */
    val CREATED: TableField<OrdersRecord, Instant?> = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "", InstantConverter())

    /**
     * The column <code>orders.created_by</code>.
     */
    val CREATED_BY: TableField<OrdersRecord, String?> = createField(DSL.name("created_by"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>orders.modified</code>.
     */
    val MODIFIED: TableField<OrdersRecord, Instant?> = createField(DSL.name("modified"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "", InstantConverter())

    /**
     * The column <code>orders.modified_by</code>.
     */
    val MODIFIED_BY: TableField<OrdersRecord, String?> = createField(DSL.name("modified_by"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>orders.order_number</code>.
     */
    val ORDER_NUMBER: TableField<OrdersRecord, String?> = createField(DSL.name("order_number"), SQLDataType.VARCHAR(20).nullable(false), this, "")

    /**
     * The column <code>orders.state</code>.
     */
    val STATE: TableField<OrdersRecord, String?> = createField(DSL.name("state"), SQLDataType.VARCHAR(16).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<OrdersRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<OrdersRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<OrdersRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>orders</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>orders</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>orders</code> table reference
     */
    constructor(): this(DSL.name("orders"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, OrdersRecord>?, parentPath: InverseForeignKey<out Record, OrdersRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, ORDERS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class OrdersPath : Orders, Path<OrdersRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, OrdersRecord>?, parentPath: InverseForeignKey<out Record, OrdersRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<OrdersRecord>): super(alias, aliased)
        override fun `as`(alias: String): OrdersPath = OrdersPath(DSL.name(alias), this)
        override fun `as`(alias: Name): OrdersPath = OrdersPath(alias, this)
        override fun `as`(alias: Table<*>): OrdersPath = OrdersPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getIndexes(): List<Index> = listOf(IDX_ORDERS_ORDER_NUMBER)
    override fun getPrimaryKey(): UniqueKey<OrdersRecord> = CONSTRAINT_C3

    private lateinit var _orderItems: OrderItemsPath

    /**
     * Get the implicit to-many join path to the <code>PUBLIC.order_items</code>
     * table
     */
    fun orderItems(): OrderItemsPath {
        if (!this::_orderItems.isInitialized)
            _orderItems = OrderItemsPath(this, null, ORDER_FK.inverseKey)

        return _orderItems;
    }

    val orderItems: OrderItemsPath
        get(): OrderItemsPath = orderItems()
    override fun `as`(alias: String): Orders = Orders(DSL.name(alias), this)
    override fun `as`(alias: Name): Orders = Orders(alias, this)
    override fun `as`(alias: Table<*>): Orders = Orders(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Orders = Orders(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Orders = Orders(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Orders = Orders(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Orders = Orders(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Orders = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Orders = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Orders = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Orders = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Orders = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Orders = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Orders = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Orders = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Orders = where(DSL.notExists(select))
}
