/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables


import java.math.BigDecimal
import java.time.Instant

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.xbery.artbeams.common.persistence.jooq.converter.InstantConverter
import org.xbery.artbeams.jooq.schema.DefaultSchema
import org.xbery.artbeams.jooq.schema.indexes.IDX_PRODUCTS_SLUG
import org.xbery.artbeams.jooq.schema.keys.CONSTRAINT_C
import org.xbery.artbeams.jooq.schema.keys.ORDERED_PRODUCT_FK
import org.xbery.artbeams.jooq.schema.keys.PRODUCT_FK
import org.xbery.artbeams.jooq.schema.tables.OrderItems.OrderItemsPath
import org.xbery.artbeams.jooq.schema.tables.UserProduct.UserProductPath
import org.xbery.artbeams.jooq.schema.tables.records.ProductsRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Products(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ProductsRecord>?,
    parentPath: InverseForeignKey<out Record, ProductsRecord>?,
    aliased: Table<ProductsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<ProductsRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>products</code>
         */
        val PRODUCTS: Products = Products()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ProductsRecord> = ProductsRecord::class.java

    /**
     * The column <code>products.id</code>.
     */
    val ID: TableField<ProductsRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>products.created</code>.
     */
    val CREATED: TableField<ProductsRecord, Instant?> = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "", InstantConverter())

    /**
     * The column <code>products.created_by</code>.
     */
    val CREATED_BY: TableField<ProductsRecord, String?> = createField(DSL.name("created_by"), SQLDataType.VARCHAR(40).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>products.modified</code>.
     */
    val MODIFIED: TableField<ProductsRecord, Instant?> = createField(DSL.name("modified"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "", InstantConverter())

    /**
     * The column <code>products.modified_by</code>.
     */
    val MODIFIED_BY: TableField<ProductsRecord, String?> = createField(DSL.name("modified_by"), SQLDataType.VARCHAR(40).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>products.slug</code>.
     */
    val SLUG: TableField<ProductsRecord, String?> = createField(DSL.name("slug"), SQLDataType.VARCHAR(128).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>products.title</code>.
     */
    val TITLE: TableField<ProductsRecord, String?> = createField(DSL.name("title"), SQLDataType.VARCHAR(128).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>products.subtitle</code>.
     */
    val SUBTITLE: TableField<ProductsRecord, String?> = createField(DSL.name("subtitle"), SQLDataType.VARCHAR(256).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>products.filename</code>.
     */
    val FILENAME: TableField<ProductsRecord, String?> = createField(DSL.name("filename"), SQLDataType.VARCHAR(128).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>products.listing_image</code>.
     */
    val LISTING_IMAGE: TableField<ProductsRecord, String?> = createField(DSL.name("listing_image"), SQLDataType.VARCHAR(128).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>products.image</code>.
     */
    val IMAGE: TableField<ProductsRecord, String?> = createField(DSL.name("image"), SQLDataType.VARCHAR(128).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>products.confirmation_mailing_group_id</code>.
     */
    val CONFIRMATION_MAILING_GROUP_ID: TableField<ProductsRecord, String?> = createField(DSL.name("confirmation_mailing_group_id"), SQLDataType.VARCHAR(128).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>products.mailing_group_id</code>.
     */
    val MAILING_GROUP_ID: TableField<ProductsRecord, String?> = createField(DSL.name("mailing_group_id"), SQLDataType.VARCHAR(128).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>products.price_regular</code>.
     */
    val PRICE_REGULAR: TableField<ProductsRecord, BigDecimal?> = createField(DSL.name("price_regular"), SQLDataType.DECIMAL(19, 4).nullable(false), this, "")

    /**
     * The column <code>products.price_discounted</code>.
     */
    val PRICE_DISCOUNTED: TableField<ProductsRecord, BigDecimal?> = createField(DSL.name("price_discounted"), SQLDataType.DECIMAL(19, 4), this, "")

    /**
     * The column <code>products.simple_shop_product_id</code>.
     */
    val SIMPLE_SHOP_PRODUCT_ID: TableField<ProductsRecord, String?> = createField(DSL.name("simple_shop_product_id"), SQLDataType.VARCHAR(64).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    private constructor(alias: Name, aliased: Table<ProductsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<ProductsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<ProductsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>products</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>products</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>products</code> table reference
     */
    constructor(): this(DSL.name("products"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ProductsRecord>?, parentPath: InverseForeignKey<out Record, ProductsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, PRODUCTS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class ProductsPath : Products, Path<ProductsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ProductsRecord>?, parentPath: InverseForeignKey<out Record, ProductsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<ProductsRecord>): super(alias, aliased)
        override fun `as`(alias: String): ProductsPath = ProductsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): ProductsPath = ProductsPath(alias, this)
        override fun `as`(alias: Table<*>): ProductsPath = ProductsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getIndexes(): List<Index> = listOf(IDX_PRODUCTS_SLUG)
    override fun getPrimaryKey(): UniqueKey<ProductsRecord> = CONSTRAINT_C

    private lateinit var _orderItems: OrderItemsPath

    /**
     * Get the implicit to-many join path to the <code>PUBLIC.order_items</code>
     * table
     */
    fun orderItems(): OrderItemsPath {
        if (!this::_orderItems.isInitialized)
            _orderItems = OrderItemsPath(this, null, ORDERED_PRODUCT_FK.inverseKey)

        return _orderItems;
    }

    val orderItems: OrderItemsPath
        get(): OrderItemsPath = orderItems()

    private lateinit var _userProduct: UserProductPath

    /**
     * Get the implicit to-many join path to the
     * <code>PUBLIC.user_product</code> table
     */
    fun userProduct(): UserProductPath {
        if (!this::_userProduct.isInitialized)
            _userProduct = UserProductPath(this, null, PRODUCT_FK.inverseKey)

        return _userProduct;
    }

    val userProduct: UserProductPath
        get(): UserProductPath = userProduct()
    override fun `as`(alias: String): Products = Products(DSL.name(alias), this)
    override fun `as`(alias: Name): Products = Products(alias, this)
    override fun `as`(alias: Table<*>): Products = Products(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Products = Products(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Products = Products(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Products = Products(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Products = Products(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Products = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Products = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Products = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Products = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Products = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Products = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Products = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Products = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Products = where(DSL.notExists(select))
}
