/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables


import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.xbery.artbeams.jooq.schema.DefaultSchema
import org.xbery.artbeams.jooq.schema.indexes.IDX_PRODUCT_COURSE_COURSE_ID
import org.xbery.artbeams.jooq.schema.indexes.IDX_PRODUCT_COURSE_PRODUCT_ID
import org.xbery.artbeams.jooq.schema.keys.CONSTRAINT_E
import org.xbery.artbeams.jooq.schema.tables.records.ProductCourseRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ProductCourse(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ProductCourseRecord>?,
    parentPath: InverseForeignKey<out Record, ProductCourseRecord>?,
    aliased: Table<ProductCourseRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<ProductCourseRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>product_course</code>
         */
        val PRODUCT_COURSE: ProductCourse = ProductCourse()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ProductCourseRecord> = ProductCourseRecord::class.java

    /**
     * The column <code>product_course.product_id</code>.
     */
    val PRODUCT_ID: TableField<ProductCourseRecord, String?> = createField(DSL.name("product_id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>product_course.course_id</code>.
     */
    val COURSE_ID: TableField<ProductCourseRecord, String?> = createField(DSL.name("course_id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<ProductCourseRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<ProductCourseRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<ProductCourseRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>product_course</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>product_course</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>product_course</code> table reference
     */
    constructor(): this(DSL.name("product_course"), null)
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getIndexes(): List<Index> = listOf(IDX_PRODUCT_COURSE_COURSE_ID, IDX_PRODUCT_COURSE_PRODUCT_ID)
    override fun getPrimaryKey(): UniqueKey<ProductCourseRecord> = CONSTRAINT_E
    override fun `as`(alias: String): ProductCourse = ProductCourse(DSL.name(alias), this)
    override fun `as`(alias: Name): ProductCourse = ProductCourse(alias, this)
    override fun `as`(alias: Table<*>): ProductCourse = ProductCourse(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ProductCourse = ProductCourse(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ProductCourse = ProductCourse(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): ProductCourse = ProductCourse(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): ProductCourse = ProductCourse(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): ProductCourse = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): ProductCourse = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): ProductCourse = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): ProductCourse = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): ProductCourse = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): ProductCourse = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): ProductCourse = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): ProductCourse = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): ProductCourse = where(DSL.notExists(select))
}
