/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables


import java.time.Instant
import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.xbery.artbeams.common.persistence.jooq.converter.InstantConverter
import org.xbery.artbeams.jooq.schema.DefaultSchema
import org.xbery.artbeams.jooq.schema.indexes.IDX_REFUND_REQUESTS_OPEN_ORDER
import org.xbery.artbeams.jooq.schema.indexes.IDX_REFUND_REQUESTS_STATUS_REQUESTED
import org.xbery.artbeams.jooq.schema.indexes.IDX_REFUND_REQUESTS_USER_REQUESTED
import org.xbery.artbeams.jooq.schema.keys.CONSTRAINT_1
import org.xbery.artbeams.jooq.schema.keys.REFUND_REQUEST_ORDER_FK
import org.xbery.artbeams.jooq.schema.keys.REFUND_REQUEST_USER_FK
import org.xbery.artbeams.jooq.schema.tables.Orders.OrdersPath
import org.xbery.artbeams.jooq.schema.tables.Users.UsersPath
import org.xbery.artbeams.jooq.schema.tables.records.RefundRequestsRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class RefundRequests(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, RefundRequestsRecord>?,
    parentPath: InverseForeignKey<out Record, RefundRequestsRecord>?,
    aliased: Table<RefundRequestsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<RefundRequestsRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>refund_requests</code>
         */
        val REFUND_REQUESTS: RefundRequests = RefundRequests()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<RefundRequestsRecord> = RefundRequestsRecord::class.java

    /**
     * The column <code>refund_requests.id</code>.
     */
    val ID: TableField<RefundRequestsRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>refund_requests.created</code>.
     */
    val CREATED: TableField<RefundRequestsRecord, Instant?> = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "", InstantConverter())

    /**
     * The column <code>refund_requests.created_by</code>.
     */
    val CREATED_BY: TableField<RefundRequestsRecord, String?> = createField(DSL.name("created_by"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>refund_requests.modified</code>.
     */
    val MODIFIED: TableField<RefundRequestsRecord, Instant?> = createField(DSL.name("modified"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "", InstantConverter())

    /**
     * The column <code>refund_requests.modified_by</code>.
     */
    val MODIFIED_BY: TableField<RefundRequestsRecord, String?> = createField(DSL.name("modified_by"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>refund_requests.order_id</code>.
     */
    val ORDER_ID: TableField<RefundRequestsRecord, String?> = createField(DSL.name("order_id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>refund_requests.user_id</code>.
     */
    val USER_ID: TableField<RefundRequestsRecord, String?> = createField(DSL.name("user_id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>refund_requests.reason</code>.
     */
    val REASON: TableField<RefundRequestsRecord, String?> = createField(DSL.name("reason"), SQLDataType.VARCHAR(2000).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>refund_requests.status</code>.
     */
    val STATUS: TableField<RefundRequestsRecord, String?> = createField(DSL.name("status"), SQLDataType.VARCHAR(16).nullable(false), this, "")

    /**
     * The column <code>refund_requests.requested_at</code>.
     */
    val REQUESTED_AT: TableField<RefundRequestsRecord, LocalDateTime?> = createField(DSL.name("requested_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>refund_requests.resolved_at</code>.
     */
    val RESOLVED_AT: TableField<RefundRequestsRecord, LocalDateTime?> = createField(DSL.name("resolved_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<RefundRequestsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<RefundRequestsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<RefundRequestsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>refund_requests</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>refund_requests</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>refund_requests</code> table reference
     */
    constructor(): this(DSL.name("refund_requests"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, RefundRequestsRecord>?, parentPath: InverseForeignKey<out Record, RefundRequestsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, REFUND_REQUESTS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class RefundRequestsPath : RefundRequests, Path<RefundRequestsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, RefundRequestsRecord>?, parentPath: InverseForeignKey<out Record, RefundRequestsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<RefundRequestsRecord>): super(alias, aliased)
        override fun `as`(alias: String): RefundRequestsPath = RefundRequestsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): RefundRequestsPath = RefundRequestsPath(alias, this)
        override fun `as`(alias: Table<*>): RefundRequestsPath = RefundRequestsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getIndexes(): List<Index> = listOf(IDX_REFUND_REQUESTS_OPEN_ORDER, IDX_REFUND_REQUESTS_STATUS_REQUESTED, IDX_REFUND_REQUESTS_USER_REQUESTED)
    override fun getPrimaryKey(): UniqueKey<RefundRequestsRecord> = CONSTRAINT_1
    override fun getReferences(): List<ForeignKey<RefundRequestsRecord, *>> = listOf(REFUND_REQUEST_ORDER_FK, REFUND_REQUEST_USER_FK)

    private lateinit var _orders: OrdersPath

    /**
     * Get the implicit join path to the <code>PUBLIC.orders</code> table.
     */
    fun orders(): OrdersPath {
        if (!this::_orders.isInitialized)
            _orders = OrdersPath(this, REFUND_REQUEST_ORDER_FK, null)

        return _orders;
    }

    val orders: OrdersPath
        get(): OrdersPath = orders()

    private lateinit var _users: UsersPath

    /**
     * Get the implicit join path to the <code>PUBLIC.users</code> table.
     */
    fun users(): UsersPath {
        if (!this::_users.isInitialized)
            _users = UsersPath(this, REFUND_REQUEST_USER_FK, null)

        return _users;
    }

    val users: UsersPath
        get(): UsersPath = users()
    override fun `as`(alias: String): RefundRequests = RefundRequests(DSL.name(alias), this)
    override fun `as`(alias: Name): RefundRequests = RefundRequests(alias, this)
    override fun `as`(alias: Table<*>): RefundRequests = RefundRequests(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): RefundRequests = RefundRequests(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): RefundRequests = RefundRequests(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): RefundRequests = RefundRequests(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): RefundRequests = RefundRequests(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): RefundRequests = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): RefundRequests = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): RefundRequests = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): RefundRequests = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): RefundRequests = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): RefundRequests = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): RefundRequests = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): RefundRequests = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): RefundRequests = where(DSL.notExists(select))
}
