/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables


import java.time.Instant

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.xbery.artbeams.common.persistence.jooq.converter.InstantConverter
import org.xbery.artbeams.jooq.schema.DefaultSchema
import org.xbery.artbeams.jooq.schema.indexes.IDX_SEARCH_ENTITY
import org.xbery.artbeams.jooq.schema.indexes.IDX_SEARCH_MODIFIED
import org.xbery.artbeams.jooq.schema.indexes.IDX_SEARCH_SLUG
import org.xbery.artbeams.jooq.schema.indexes.IDX_SEARCH_VALIDITY
import org.xbery.artbeams.jooq.schema.keys.CONSTRAINT_1B
import org.xbery.artbeams.jooq.schema.tables.records.SearchIndexRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SearchIndex(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, SearchIndexRecord>?,
    parentPath: InverseForeignKey<out Record, SearchIndexRecord>?,
    aliased: Table<SearchIndexRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<SearchIndexRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>search_index</code>
         */
        val SEARCH_INDEX: SearchIndex = SearchIndex()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<SearchIndexRecord> = SearchIndexRecord::class.java

    /**
     * The column <code>search_index.id</code>.
     */
    val ID: TableField<SearchIndexRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>search_index.entity_type</code>.
     */
    val ENTITY_TYPE: TableField<SearchIndexRecord, String?> = createField(DSL.name("entity_type"), SQLDataType.VARCHAR(20).nullable(false), this, "")

    /**
     * The column <code>search_index.entity_id</code>.
     */
    val ENTITY_ID: TableField<SearchIndexRecord, String?> = createField(DSL.name("entity_id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>search_index.title</code>.
     */
    val TITLE: TableField<SearchIndexRecord, String?> = createField(DSL.name("title"), SQLDataType.VARCHAR(500).nullable(false), this, "")

    /**
     * The column <code>search_index.description</code>.
     */
    val DESCRIPTION: TableField<SearchIndexRecord, String?> = createField(DSL.name("description"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>search_index.keywords</code>.
     */
    val KEYWORDS: TableField<SearchIndexRecord, String?> = createField(DSL.name("keywords"), SQLDataType.VARCHAR(1000), this, "")

    /**
     * The column <code>search_index.slug</code>.
     */
    val SLUG: TableField<SearchIndexRecord, String?> = createField(DSL.name("slug"), SQLDataType.VARCHAR(128), this, "")

    /**
     * The column <code>search_index.search_vector</code>.
     */
    val SEARCH_VECTOR: TableField<SearchIndexRecord, String?> = createField(DSL.name("search_vector"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>search_index.metadata</code>.
     */
    val METADATA: TableField<SearchIndexRecord, String?> = createField(DSL.name("metadata"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>search_index.valid_from</code>.
     */
    val VALID_FROM: TableField<SearchIndexRecord, Instant?> = createField(DSL.name("valid_from"), SQLDataType.LOCALDATETIME(6), this, "", InstantConverter())

    /**
     * The column <code>search_index.valid_to</code>.
     */
    val VALID_TO: TableField<SearchIndexRecord, Instant?> = createField(DSL.name("valid_to"), SQLDataType.LOCALDATETIME(6), this, "", InstantConverter())

    /**
     * The column <code>search_index.created</code>.
     */
    val CREATED: TableField<SearchIndexRecord, Instant?> = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "", InstantConverter())

    /**
     * The column <code>search_index.modified</code>.
     */
    val MODIFIED: TableField<SearchIndexRecord, Instant?> = createField(DSL.name("modified"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "", InstantConverter())

    private constructor(alias: Name, aliased: Table<SearchIndexRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<SearchIndexRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<SearchIndexRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>search_index</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>search_index</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>search_index</code> table reference
     */
    constructor(): this(DSL.name("search_index"), null)
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getIndexes(): List<Index> = listOf(IDX_SEARCH_ENTITY, IDX_SEARCH_MODIFIED, IDX_SEARCH_SLUG, IDX_SEARCH_VALIDITY)
    override fun getPrimaryKey(): UniqueKey<SearchIndexRecord> = CONSTRAINT_1B
    override fun `as`(alias: String): SearchIndex = SearchIndex(DSL.name(alias), this)
    override fun `as`(alias: Name): SearchIndex = SearchIndex(alias, this)
    override fun `as`(alias: Table<*>): SearchIndex = SearchIndex(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): SearchIndex = SearchIndex(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): SearchIndex = SearchIndex(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): SearchIndex = SearchIndex(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): SearchIndex = SearchIndex(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): SearchIndex = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): SearchIndex = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): SearchIndex = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): SearchIndex = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): SearchIndex = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): SearchIndex = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): SearchIndex = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): SearchIndex = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): SearchIndex = where(DSL.notExists(select))
}
