/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables


import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.xbery.artbeams.jooq.schema.DefaultSchema
import org.xbery.artbeams.jooq.schema.keys.CONSTRAINT_BD
import org.xbery.artbeams.jooq.schema.tables.records.SequencesRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Sequences(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, SequencesRecord>?,
    aliased: Table<SequencesRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<SequencesRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>sequences</code>
         */
        val SEQUENCES: Sequences = Sequences()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<SequencesRecord> = SequencesRecord::class.java

    /**
     * The column <code>sequences.sequence_name</code>.
     */
    val SEQUENCE_NAME: TableField<SequencesRecord, String?> = createField(DSL.name("sequence_name"), SQLDataType.VARCHAR(20).nullable(false), this, "")

    /**
     * The column <code>sequences.next_value</code>.
     */
    val NEXT_VALUE: TableField<SequencesRecord, Long?> = createField(DSL.name("next_value"), SQLDataType.BIGINT.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<SequencesRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<SequencesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>sequences</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>sequences</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>sequences</code> table reference
     */
    constructor(): this(DSL.name("sequences"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, SequencesRecord>): this(Internal.createPathAlias(child, key), child, key, SEQUENCES, null)
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getPrimaryKey(): UniqueKey<SequencesRecord> = CONSTRAINT_BD
    override fun `as`(alias: String): Sequences = Sequences(DSL.name(alias), this)
    override fun `as`(alias: Name): Sequences = Sequences(alias, this)
    override fun `as`(alias: Table<*>): Sequences = Sequences(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Sequences = Sequences(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Sequences = Sequences(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Sequences = Sequences(name.getQualifiedName(), null)
}
