/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables


import java.time.Instant

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.xbery.artbeams.common.persistence.jooq.converter.InstantConverter
import org.xbery.artbeams.jooq.schema.DefaultSchema
import org.xbery.artbeams.jooq.schema.indexes.IDX_SYSTEM_EVENT_LOG_ENTITY
import org.xbery.artbeams.jooq.schema.indexes.IDX_SYSTEM_EVENT_LOG_SEVERITY_TIME
import org.xbery.artbeams.jooq.schema.indexes.IDX_SYSTEM_EVENT_LOG_TIME
import org.xbery.artbeams.jooq.schema.indexes.IDX_SYSTEM_EVENT_LOG_TYPE_TIME
import org.xbery.artbeams.jooq.schema.indexes.IDX_SYSTEM_EVENT_LOG_USER_TIME
import org.xbery.artbeams.jooq.schema.keys.CONSTRAINT_6E
import org.xbery.artbeams.jooq.schema.tables.records.SystemEventLogRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SystemEventLog(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, SystemEventLogRecord>?,
    parentPath: InverseForeignKey<out Record, SystemEventLogRecord>?,
    aliased: Table<SystemEventLogRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<SystemEventLogRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>system_event_log</code>
         */
        val SYSTEM_EVENT_LOG: SystemEventLog = SystemEventLog()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<SystemEventLogRecord> = SystemEventLogRecord::class.java

    /**
     * The column <code>system_event_log.id</code>.
     */
    val ID: TableField<SystemEventLogRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>system_event_log.event_time</code>.
     */
    val EVENT_TIME: TableField<SystemEventLogRecord, Instant?> = createField(DSL.name("event_time"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "", InstantConverter())

    /**
     * The column <code>system_event_log.severity</code>.
     */
    val SEVERITY: TableField<SystemEventLogRecord, String?> = createField(DSL.name("severity"), SQLDataType.VARCHAR(16).nullable(false), this, "")

    /**
     * The column <code>system_event_log.event_type</code>.
     */
    val EVENT_TYPE: TableField<SystemEventLogRecord, String?> = createField(DSL.name("event_type"), SQLDataType.VARCHAR(80).nullable(false), this, "")

    /**
     * The column <code>system_event_log.origin</code>.
     */
    val ORIGIN: TableField<SystemEventLogRecord, String?> = createField(DSL.name("origin"), SQLDataType.VARCHAR(60).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>system_event_log.message</code>.
     */
    val MESSAGE: TableField<SystemEventLogRecord, String?> = createField(DSL.name("message"), SQLDataType.VARCHAR(2000).nullable(false), this, "")

    /**
     * The column <code>system_event_log.details</code>.
     */
    val DETAILS: TableField<SystemEventLogRecord, String?> = createField(DSL.name("details"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "")

    /**
     * The column <code>system_event_log.stack_trace</code>.
     */
    val STACK_TRACE: TableField<SystemEventLogRecord, String?> = createField(DSL.name("stack_trace"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "")

    /**
     * The column <code>system_event_log.entity_type</code>.
     */
    val ENTITY_TYPE: TableField<SystemEventLogRecord, String?> = createField(DSL.name("entity_type"), SQLDataType.VARCHAR(20).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>system_event_log.entity_id</code>.
     */
    val ENTITY_ID: TableField<SystemEventLogRecord, String?> = createField(DSL.name("entity_id"), SQLDataType.VARCHAR(40).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>system_event_log.user_id</code>.
     */
    val USER_ID: TableField<SystemEventLogRecord, String?> = createField(DSL.name("user_id"), SQLDataType.VARCHAR(40).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>system_event_log.ip_address</code>.
     */
    val IP_ADDRESS: TableField<SystemEventLogRecord, String?> = createField(DSL.name("ip_address"), SQLDataType.VARCHAR(60).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>system_event_log.user_agent</code>.
     */
    val USER_AGENT: TableField<SystemEventLogRecord, String?> = createField(DSL.name("user_agent"), SQLDataType.VARCHAR(200).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>system_event_log.correlation_id</code>.
     */
    val CORRELATION_ID: TableField<SystemEventLogRecord, String?> = createField(DSL.name("correlation_id"), SQLDataType.VARCHAR(64).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    private constructor(alias: Name, aliased: Table<SystemEventLogRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<SystemEventLogRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<SystemEventLogRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>system_event_log</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>system_event_log</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>system_event_log</code> table reference
     */
    constructor(): this(DSL.name("system_event_log"), null)
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getIndexes(): List<Index> = listOf(IDX_SYSTEM_EVENT_LOG_ENTITY, IDX_SYSTEM_EVENT_LOG_SEVERITY_TIME, IDX_SYSTEM_EVENT_LOG_TIME, IDX_SYSTEM_EVENT_LOG_TYPE_TIME, IDX_SYSTEM_EVENT_LOG_USER_TIME)
    override fun getPrimaryKey(): UniqueKey<SystemEventLogRecord> = CONSTRAINT_6E
    override fun `as`(alias: String): SystemEventLog = SystemEventLog(DSL.name(alias), this)
    override fun `as`(alias: Name): SystemEventLog = SystemEventLog(alias, this)
    override fun `as`(alias: Table<*>): SystemEventLog = SystemEventLog(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): SystemEventLog = SystemEventLog(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): SystemEventLog = SystemEventLog(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): SystemEventLog = SystemEventLog(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): SystemEventLog = SystemEventLog(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): SystemEventLog = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): SystemEventLog = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): SystemEventLog = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): SystemEventLog = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): SystemEventLog = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): SystemEventLog = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): SystemEventLog = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): SystemEventLog = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): SystemEventLog = where(DSL.notExists(select))
}
