/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables


import java.time.Instant

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.xbery.artbeams.common.persistence.jooq.converter.InstantConverter
import org.xbery.artbeams.jooq.schema.DefaultSchema
import org.xbery.artbeams.jooq.schema.indexes.IDX_USER_ACTIVITY_LOG_ACTION_TIME
import org.xbery.artbeams.jooq.schema.indexes.IDX_USER_ACTIVITY_LOG_ACTION_TYPE
import org.xbery.artbeams.jooq.schema.indexes.IDX_USER_ACTIVITY_LOG_ENTITY
import org.xbery.artbeams.jooq.schema.indexes.IDX_USER_ACTIVITY_LOG_USER_ID
import org.xbery.artbeams.jooq.schema.indexes.IDX_USER_ACTIVITY_LOG_USER_TIME
import org.xbery.artbeams.jooq.schema.keys.CONSTRAINT_1
import org.xbery.artbeams.jooq.schema.keys.USER_ACTIVITY_LOG_USER_FK
import org.xbery.artbeams.jooq.schema.tables.Users.UsersPath
import org.xbery.artbeams.jooq.schema.tables.records.UserActivityLogRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UserActivityLog(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, UserActivityLogRecord>?,
    parentPath: InverseForeignKey<out Record, UserActivityLogRecord>?,
    aliased: Table<UserActivityLogRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<UserActivityLogRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>user_activity_log</code>
         */
        val USER_ACTIVITY_LOG: UserActivityLog = UserActivityLog()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<UserActivityLogRecord> = UserActivityLogRecord::class.java

    /**
     * The column <code>user_activity_log.id</code>.
     */
    val ID: TableField<UserActivityLogRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>user_activity_log.user_id</code>.
     */
    val USER_ID: TableField<UserActivityLogRecord, String?> = createField(DSL.name("user_id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>user_activity_log.action_type</code>.
     */
    val ACTION_TYPE: TableField<UserActivityLogRecord, String?> = createField(DSL.name("action_type"), SQLDataType.VARCHAR(32).nullable(false), this, "")

    /**
     * The column <code>user_activity_log.action_time</code>.
     */
    val ACTION_TIME: TableField<UserActivityLogRecord, Instant?> = createField(DSL.name("action_time"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "", InstantConverter())

    /**
     * The column <code>user_activity_log.entity_type</code>.
     */
    val ENTITY_TYPE: TableField<UserActivityLogRecord, String?> = createField(DSL.name("entity_type"), SQLDataType.VARCHAR(20).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>user_activity_log.entity_id</code>.
     */
    val ENTITY_ID: TableField<UserActivityLogRecord, String?> = createField(DSL.name("entity_id"), SQLDataType.VARCHAR(40).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>user_activity_log.ip_address</code>.
     */
    val IP_ADDRESS: TableField<UserActivityLogRecord, String?> = createField(DSL.name("ip_address"), SQLDataType.VARCHAR(60).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>user_activity_log.user_agent</code>.
     */
    val USER_AGENT: TableField<UserActivityLogRecord, String?> = createField(DSL.name("user_agent"), SQLDataType.VARCHAR(200).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>user_activity_log.details</code>.
     */
    val DETAILS: TableField<UserActivityLogRecord, String?> = createField(DSL.name("details"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "")

    private constructor(alias: Name, aliased: Table<UserActivityLogRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<UserActivityLogRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<UserActivityLogRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>user_activity_log</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>user_activity_log</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>user_activity_log</code> table reference
     */
    constructor(): this(DSL.name("user_activity_log"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, UserActivityLogRecord>?, parentPath: InverseForeignKey<out Record, UserActivityLogRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, USER_ACTIVITY_LOG, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class UserActivityLogPath : UserActivityLog, Path<UserActivityLogRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, UserActivityLogRecord>?, parentPath: InverseForeignKey<out Record, UserActivityLogRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<UserActivityLogRecord>): super(alias, aliased)
        override fun `as`(alias: String): UserActivityLogPath = UserActivityLogPath(DSL.name(alias), this)
        override fun `as`(alias: Name): UserActivityLogPath = UserActivityLogPath(alias, this)
        override fun `as`(alias: Table<*>): UserActivityLogPath = UserActivityLogPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getIndexes(): List<Index> = listOf(IDX_USER_ACTIVITY_LOG_ACTION_TIME, IDX_USER_ACTIVITY_LOG_ACTION_TYPE, IDX_USER_ACTIVITY_LOG_ENTITY, IDX_USER_ACTIVITY_LOG_USER_ID, IDX_USER_ACTIVITY_LOG_USER_TIME)
    override fun getPrimaryKey(): UniqueKey<UserActivityLogRecord> = CONSTRAINT_1
    override fun getReferences(): List<ForeignKey<UserActivityLogRecord, *>> = listOf(USER_ACTIVITY_LOG_USER_FK)

    private lateinit var _users: UsersPath

    /**
     * Get the implicit join path to the <code>PUBLIC.users</code> table.
     */
    fun users(): UsersPath {
        if (!this::_users.isInitialized)
            _users = UsersPath(this, USER_ACTIVITY_LOG_USER_FK, null)

        return _users;
    }

    val users: UsersPath
        get(): UsersPath = users()
    override fun `as`(alias: String): UserActivityLog = UserActivityLog(DSL.name(alias), this)
    override fun `as`(alias: Name): UserActivityLog = UserActivityLog(alias, this)
    override fun `as`(alias: Table<*>): UserActivityLog = UserActivityLog(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): UserActivityLog = UserActivityLog(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): UserActivityLog = UserActivityLog(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): UserActivityLog = UserActivityLog(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): UserActivityLog = UserActivityLog(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): UserActivityLog = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): UserActivityLog = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): UserActivityLog = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): UserActivityLog = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): UserActivityLog = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): UserActivityLog = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): UserActivityLog = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): UserActivityLog = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): UserActivityLog = where(DSL.notExists(select))
}
