/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables


import kotlin.collections.List

import kotlinx.datetime.Instant

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.xbery.artbeams.common.persistence.jooq.converter.InstantConverter
import org.xbery.artbeams.jooq.schema.DefaultSchema
import org.xbery.artbeams.jooq.schema.keys.CONSTRAINT_48
import org.xbery.artbeams.jooq.schema.keys.PRODUCT_FK
import org.xbery.artbeams.jooq.schema.keys.USER_FK
import org.xbery.artbeams.jooq.schema.tables.records.UserProductRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UserProduct(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, UserProductRecord>?,
    aliased: Table<UserProductRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<UserProductRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>user_product</code>
         */
        val USER_PRODUCT: UserProduct = UserProduct()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<UserProductRecord> = UserProductRecord::class.java

    /**
     * The column <code>user_product.id</code>.
     */
    val ID: TableField<UserProductRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>user_product.user_id</code>.
     */
    val USER_ID: TableField<UserProductRecord, String?> = createField(DSL.name("user_id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>user_product.product_id</code>.
     */
    val PRODUCT_ID: TableField<UserProductRecord, String?> = createField(DSL.name("product_id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>user_product.created</code>.
     */
    val CREATED: TableField<UserProductRecord, Instant?> = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "", InstantConverter())

    private constructor(alias: Name, aliased: Table<UserProductRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<UserProductRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>user_product</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>user_product</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>user_product</code> table reference
     */
    constructor(): this(DSL.name("user_product"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, UserProductRecord>): this(Internal.createPathAlias(child, key), child, key, USER_PRODUCT, null)
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getPrimaryKey(): UniqueKey<UserProductRecord> = CONSTRAINT_48
    override fun getReferences(): List<ForeignKey<UserProductRecord, *>> = listOf(USER_FK, PRODUCT_FK)

    private lateinit var _users: Users
    private lateinit var _products: Products

    /**
     * Get the implicit join path to the <code>PUBLIC.users</code> table.
     */
    fun users(): Users {
        if (!this::_users.isInitialized)
            _users = Users(this, USER_FK)

        return _users;
    }

    val users: Users
        get(): Users = users()

    /**
     * Get the implicit join path to the <code>PUBLIC.products</code> table.
     */
    fun products(): Products {
        if (!this::_products.isInitialized)
            _products = Products(this, PRODUCT_FK)

        return _products;
    }

    val products: Products
        get(): Products = products()
    override fun `as`(alias: String): UserProduct = UserProduct(DSL.name(alias), this)
    override fun `as`(alias: Name): UserProduct = UserProduct(alias, this)
    override fun `as`(alias: Table<*>): UserProduct = UserProduct(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): UserProduct = UserProduct(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): UserProduct = UserProduct(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): UserProduct = UserProduct(name.getQualifiedName(), null)
}
