/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables


import java.time.LocalDate
import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.xbery.artbeams.jooq.schema.DefaultSchema
import org.xbery.artbeams.jooq.schema.indexes.IDX_USER_ACCESS_UNIQUE
import org.xbery.artbeams.jooq.schema.keys.CONSTRAINT_D
import org.xbery.artbeams.jooq.schema.tables.records.UserAccessRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UserAccess(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, UserAccessRecord>?,
    aliased: Table<UserAccessRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<UserAccessRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>user_access</code>
         */
        val USER_ACCESS: UserAccess = UserAccess()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<UserAccessRecord> = UserAccessRecord::class.java

    /**
     * The column <code>user_access.id</code>.
     */
    val ID: TableField<UserAccessRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>user_access.access_time</code>.
     */
    val ACCESS_TIME: TableField<UserAccessRecord, LocalDateTime?> = createField(DSL.name("access_time"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>user_access.access_date</code>.
     */
    val ACCESS_DATE: TableField<UserAccessRecord, LocalDate?> = createField(DSL.name("access_date"), SQLDataType.LOCALDATE.nullable(false), this, "")

    /**
     * The column <code>user_access.ip</code>.
     */
    val IP: TableField<UserAccessRecord, String?> = createField(DSL.name("ip"), SQLDataType.VARCHAR(60).nullable(false), this, "")

    /**
     * The column <code>user_access.user_agent</code>.
     */
    val USER_AGENT: TableField<UserAccessRecord, String?> = createField(DSL.name("user_agent"), SQLDataType.VARCHAR(200).nullable(false), this, "")

    /**
     * The column <code>user_access.entity_type</code>.
     */
    val ENTITY_TYPE: TableField<UserAccessRecord, String?> = createField(DSL.name("entity_type"), SQLDataType.VARCHAR(20).nullable(false), this, "")

    /**
     * The column <code>user_access.entity_id</code>.
     */
    val ENTITY_ID: TableField<UserAccessRecord, String?> = createField(DSL.name("entity_id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<UserAccessRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<UserAccessRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>user_access</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>user_access</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>user_access</code> table reference
     */
    constructor(): this(DSL.name("user_access"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, UserAccessRecord>): this(Internal.createPathAlias(child, key), child, key, USER_ACCESS, null)
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getIndexes(): List<Index> = listOf(IDX_USER_ACCESS_UNIQUE)
    override fun getPrimaryKey(): UniqueKey<UserAccessRecord> = CONSTRAINT_D
    override fun `as`(alias: String): UserAccess = UserAccess(DSL.name(alias), this)
    override fun `as`(alias: Name): UserAccess = UserAccess(alias, this)
    override fun `as`(alias: Table<*>): UserAccess = UserAccess(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): UserAccess = UserAccess(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): UserAccess = UserAccess(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): UserAccess = UserAccess(name.getQualifiedName(), null)
}
