/*
 * This file is generated by jOOQ.
 */
package org.xbery.artbeams.jooq.schema.tables


import java.time.Instant
import java.time.LocalDate

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.xbery.artbeams.common.persistence.jooq.converter.InstantConverter
import org.xbery.artbeams.jooq.schema.DefaultSchema
import org.xbery.artbeams.jooq.schema.indexes.IDX_USER_ACCESS_UNIQUE
import org.xbery.artbeams.jooq.schema.keys.CONSTRAINT_D
import org.xbery.artbeams.jooq.schema.tables.records.UserAccessRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UserAccess(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, UserAccessRecord>?,
    parentPath: InverseForeignKey<out Record, UserAccessRecord>?,
    aliased: Table<UserAccessRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<UserAccessRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>user_access</code>
         */
        val USER_ACCESS: UserAccess = UserAccess()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<UserAccessRecord> = UserAccessRecord::class.java

    /**
     * The column <code>user_access.id</code>.
     */
    val ID: TableField<UserAccessRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>user_access.access_time</code>.
     */
    val ACCESS_TIME: TableField<UserAccessRecord, Instant?> = createField(DSL.name("access_time"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "", InstantConverter())

    /**
     * The column <code>user_access.access_date</code>.
     */
    val ACCESS_DATE: TableField<UserAccessRecord, LocalDate?> = createField(DSL.name("access_date"), SQLDataType.LOCALDATE.nullable(false), this, "")

    /**
     * The column <code>user_access.ip</code>.
     */
    val IP: TableField<UserAccessRecord, String?> = createField(DSL.name("ip"), SQLDataType.VARCHAR(60).nullable(false), this, "")

    /**
     * The column <code>user_access.user_agent</code>.
     */
    val USER_AGENT: TableField<UserAccessRecord, String?> = createField(DSL.name("user_agent"), SQLDataType.VARCHAR(200).nullable(false), this, "")

    /**
     * The column <code>user_access.entity_type</code>.
     */
    val ENTITY_TYPE: TableField<UserAccessRecord, String?> = createField(DSL.name("entity_type"), SQLDataType.VARCHAR(20).nullable(false), this, "")

    /**
     * The column <code>user_access.entity_id</code>.
     */
    val ENTITY_ID: TableField<UserAccessRecord, String?> = createField(DSL.name("entity_id"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<UserAccessRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<UserAccessRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<UserAccessRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>user_access</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>user_access</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>user_access</code> table reference
     */
    constructor(): this(DSL.name("user_access"), null)
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getIndexes(): List<Index> = listOf(IDX_USER_ACCESS_UNIQUE)
    override fun getPrimaryKey(): UniqueKey<UserAccessRecord> = CONSTRAINT_D
    override fun `as`(alias: String): UserAccess = UserAccess(DSL.name(alias), this)
    override fun `as`(alias: Name): UserAccess = UserAccess(alias, this)
    override fun `as`(alias: Table<*>): UserAccess = UserAccess(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): UserAccess = UserAccess(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): UserAccess = UserAccess(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): UserAccess = UserAccess(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): UserAccess = UserAccess(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): UserAccess = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): UserAccess = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): UserAccess = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): UserAccess = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): UserAccess = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): UserAccess = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): UserAccess = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): UserAccess = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): UserAccess = where(DSL.notExists(select))
}
