INSERT INTO localisation (entry_key, entry_value) VALUES ('author.name', '???');
INSERT INTO localisation (entry_key, entry_value) VALUES ('author.about', '???');
INSERT INTO localisation (entry_key, entry_value) VALUES ('author.img.src', '/media/author.jpg');
INSERT INTO localisation (entry_key, entry_value) VALUES ('favicon.img.src', '/media/favicon.ico');
INSERT INTO localisation (entry_key, entry_value) VALUES ('menu.item1.title', '???');
INSERT INTO localisation (entry_key, entry_value) VALUES ('menu.item1.url', '???');
INSERT INTO localisation (entry_key, entry_value) VALUES ('menu.item2.title', '???');
INSERT INTO localisation (entry_key, entry_value) VALUES ('menu.item2.url', '???');
INSERT INTO localisation (entry_key, entry_value) VALUES ('menu.item3.title', '???');
INSERT INTO localisation (entry_key, entry_value) VALUES ('menu.item3.url', '???');
INSERT INTO localisation (entry_key, entry_value) VALUES ('administration', 'Administrace');
INSERT INTO localisation (entry_key, entry_value) VALUES ('category', 'Kategorie');
INSERT INTO localisation (entry_key, entry_value) VALUES ('categories.url.base', '/kategorie');
INSERT INTO localisation (entry_key, entry_value) VALUES ('logout', 'Odhlásit');
INSERT INTO localisation (entry_key, entry_value) VALUES ('search', 'Hledat'); 
INSERT INTO localisation (entry_key, entry_value) VALUES ('headline.portrait.url', '???');
INSERT INTO localisation (entry_key, entry_value) VALUES ('headline.portrait.src', '???');
INSERT INTO localisation (entry_key, entry_value) VALUES ('headline.offer.header', '???');
INSERT INTO localisation (entry_key, entry_value) VALUES ('headline.offer.url', '???');
INSERT INTO localisation (entry_key, entry_value) VALUES ('headline.offer.img.src', '???');
INSERT INTO localisation (entry_key, entry_value) VALUES ('headline.offer.img.alt', '???');
INSERT INTO localisation (entry_key, entry_value) VALUES ('headline.offer.description', '???');
INSERT INTO localisation (entry_key, entry_value) VALUES ('headline.offer.action', '???');

INSERT INTO localisation (entry_key, entry_value) VALUES ('fb.app-id', '???');
INSERT INTO localisation (entry_key, entry_value) VALUES ('fb.page.url', '???');
INSERT INTO localisation (entry_key, entry_value) VALUES ('fb.page.title', '???');
INSERT INTO localisation (entry_key, entry_value) VALUES ('fb.sdk.url', '???');
INSERT INTO localisation (entry_key, entry_value) VALUES ('google-tag.url', '???');
INSERT INTO localisation (entry_key, entry_value) VALUES ('google-tag.config', '???');
INSERT INTO localisation (entry_key, entry_value) VALUES ('mailer-lite.id1', '???');
INSERT INTO localisation (entry_key, entry_value) VALUES ('mailer-lite.id2', '???');
INSERT INTO localisation (entry_key, entry_value) VALUES ('mailer-lite.form', '???');
INSERT INTO localisation (entry_key, entry_value) VALUES ('mailer-lite.popup-form', '???');

INSERT INTO localisation (entry_key, entry_value) VALUES ('website.about.header', '???');
INSERT INTO localisation (entry_key, entry_value) VALUES ('website.title', '???');
INSERT INTO localisation (entry_key, entry_value) VALUES ('website.purpose', '???');
INSERT INTO localisation (entry_key, entry_value) VALUES ('website.description', '???');
INSERT INTO localisation (entry_key, entry_value) VALUES ('website.disclaimer', '???');
INSERT INTO localisation (entry_key, entry_value) VALUES ('website.keywords', '???');
INSERT INTO localisation (entry_key, entry_value) VALUES ('website.locale', 'cs_CZ');

INSERT INTO localisation (entry_key, entry_value) VALUES ('articles.newest', 'Nejnovější příspěvky');
INSERT INTO localisation (entry_key, entry_value) VALUES ('articles.rubrics', 'Rubriky');
INSERT INTO localisation (entry_key, entry_value) VALUES ('social.networks', 'Sociální sítě');

INSERT INTO localisation (entry_key, entry_value) VALUES ('personal-data.protection.url', '/ochrana-osobnich-udaju');
INSERT INTO localisation (entry_key, entry_value) VALUES ('personal-data.protection.title', 'Zpracování a ochrana osobních údajů');
INSERT INTO localisation (entry_key, entry_value) VALUES ('goto.up', 'Nahoru');
INSERT INTO localisation (entry_key, entry_value) VALUES ('cookies.info', 'Na webu používáme cookies. Prohlížením webu s jejich používáním souhlasíte.');
INSERT INTO localisation (entry_key, entry_value) VALUES ('cookies.info.more', 'Více informací');
INSERT INTO localisation (entry_key, entry_value) VALUES ('cookies.agreement.action', 'Rozumím');
